# -*- coding: utf-8 -*-
"""Build embedded UI phrase and privacy catalogs. English text is the key."""
import json
from pathlib import Path

LANGS = ["es", "fr", "de", "pt", "it", "ru", "ja", "ko", "zh-Hans"]

# Each value is es, fr, de, pt, it, ru, ja, ko, zh-Hans.
P = {
"SharpShot Settings": ("Ajustes de SharpShot", "Paramètres de SharpShot", "SharpShot-Einstellungen", "Configurações do SharpShot", "Impostazioni di SharpShot", "Параметры SharpShot", "SharpShot の設定", "SharpShot 설정", "SharpShot 设置"),
"Settings": ("Ajustes", "Paramètres", "Einstellungen", "Configurações", "Impostazioni", "Настройки", "設定", "설정", "设置"),
"General": ("General", "Général", "Allgemein", "Geral", "Generale", "Общие", "一般", "일반", "常规"),
"Capture": ("Captura", "Capture", "Aufnahme", "Captura", "Acquisizione", "Захват", "キャプチャ", "캡처", "截图"),
"Recording": ("Grabación", "Enregistrement", "Aufnahme", "Gravação", "Registrazione", "Запись", "録画", "녹화", "录制"),
"Dashboard": ("Panel", "Tableau de bord", "Übersicht", "Painel", "Pannello", "Панель", "ダッシュボード", "대시보드", "仪表盘"),
"Appearance": ("Apariencia", "Apparence", "Darstellung", "Aparência", "Aspetto", "Оформление", "外観", "모양", "外观"),
"Hotkeys": ("Atajos", "Raccourcis", "Tastenkürzel", "Atalhos", "Scorciatoie", "Горячие клавиши", "ホットキー", "단축키", "热键"),
"Updates": ("Actualizaciones", "Mises à jour", "Updates", "Atualizações", "Aggiornamenti", "Обновления", "更新", "업데이트", "更新"),
"Language": ("Idioma", "Langue", "Sprache", "Idioma", "Lingua", "Язык", "言語", "언어", "语言"),
"App language": ("Idioma de la app", "Langue de l'application", "App-Sprache", "Idioma do aplicativo", "Lingua dell'app", "Язык приложения", "アプリの言語", "앱 언어", "应用语言"),
"Changes SharpShot's menus, settings, tooltips, and the in-app privacy policy. OCR language is separate.": (
"Cambia los menús, ajustes, descripciones y la política de privacidad de SharpShot. El idioma de OCR es aparte.",
"Change les menus, les paramètres, les info-bulles et la politique de confidentialité dans l'app. La langue OCR est séparée.",
"Ändert Menüs, Einstellungen, Kurzinfos und die Datenschutzrichtlinie in der App. Die OCR-Sprache ist getrennt.",
"Altera os menus, as configurações, as dicas e a política de privacidade no aplicativo. O idioma do OCR é separado.",
"Cambia menu, impostazioni, descrizioni e l'informativa privacy nell'app. La lingua OCR è separata.",
"Меняет меню, параметры, подсказки и политику конфиденциальности в приложении. Язык OCR задаётся отдельно.",
"メニュー、設定、ツールヒント、アプリ内のプライバシー ポリシーを切り替えます。OCR の言語は別です。",
"메뉴, 설정, 도구 설명, 앱 안의 개인정보 처리방침을 바꿉니다. OCR 언어는 별도입니다.",
"切换 SharpShot 的菜单、设置、提示和应用内隐私政策。OCR 语言单独设置。",
),
"OCR language": ("Idioma de OCR", "Langue OCR", "OCR-Sprache", "Idioma do OCR", "Lingua OCR", "Язык OCR", "OCR の言語", "OCR 언어", "OCR 语言"),
"Auto reads English, Spanish, French, German, Portuguese, and Italian together. Pick Japanese, Chinese, Korean, or Russian when the screen uses that script.": (
"Automático lee inglés, español, francés, alemán, portugués e italiano a la vez. Elige japonés, chino, coreano o ruso si la pantalla usa esa escritura.",
"Auto lit l'anglais, l'espagnol, le français, l'allemand, le portugais et l'italien ensemble. Choisissez le japonais, le chinois, le coréen ou le russe si l'écran utilise cette écriture.",
"Automatisch liest Englisch, Spanisch, Französisch, Deutsch, Portugiesisch und Italienisch zusammen. Wählen Sie Japanisch, Chinesisch, Koreanisch oder Russisch, wenn der Bildschirm diese Schrift nutzt.",
"Automático lê inglês, espanhol, francês, alemão, português e italiano juntos. Escolha japonês, chinês, coreano ou russo quando a tela usar essa escrita.",
"Automatico legge insieme inglese, spagnolo, francese, tedesco, portoghese e italiano. Scegli giapponese, cinese, coreano o russo se lo schermo usa quella scrittura.",
"Авто читает английский, испанский, французский, немецкий, португальский и итальянский вместе. Выберите японский, китайский, корейский или русский, если на экране эта письменность.",
"自動は英語・スペイン語・フランス語・ドイツ語・ポルトガル語・イタリア語をまとめて読みます。画面がその文字のときは日本語、中国語、韓国語、ロシア語を選んでください。",
"자동은 영어, 스페인어, 프랑스어, 독일어, 포르투갈어, 이탈리아어를 함께 읽습니다. 화면이 그 문자면 일본어, 중국어, 한국어, 러시아어를 고르세요.",
"自动会同时识别英语、西班牙语、法语、德语、葡萄牙语和意大利语。屏幕使用日文、中文、韩文或俄文时请选择对应语言。",
),
"Storage": ("Almacenamiento", "Stockage", "Speicher", "Armazenamento", "Archiviazione", "Хранилище", "保存先", "저장", "存储"),
"Save Path:": ("Ruta de guardado:", "Dossier d'enregistrement :", "Speicherpfad:", "Caminho para salvar:", "Percorso di salvataggio:", "Папка сохранения:", "保存先:", "저장 경로:", "保存路径："),
"Browse": ("Examinar", "Parcourir", "Durchsuchen", "Procurar", "Sfoglia", "Обзор", "参照", "찾아보기", "浏览"),
"Browse…": ("Examinar…", "Parcourir…", "Durchsuchen…", "Procurar…", "Sfoglia…", "Обзор…", "参照…", "찾아보기…", "浏览…"),
"Screenshot Format:": ("Formato de captura:", "Format de capture :", "Bildformat:", "Formato da captura:", "Formato screenshot:", "Формат снимка:", "画像形式:", "스크린샷 형식:", "截图格式："),
"Startup & tray": ("Inicio y bandeja", "Démarrage et barre", "Start und Infobereich", "Inicialização e bandeja", "Avvio e area di notifica", "Автозапуск и трей", "起動とトレイ", "시작 및 트레이", "启动和托盘"),
"Enable Global Hotkeys": ("Activar atajos globales", "Activer les raccourcis globaux", "Globale Tastenkürzel aktivieren", "Ativar atalhos globais", "Abilita scorciatoie globali", "Включить глобальные горячие клавиши", "グローバル ホットキーを有効にする", "전역 단축키 사용", "启用全局热键"),
"Start Minimized": ("Iniciar minimizado", "Démarrer réduit", "Minimiert starten", "Iniciar minimizado", "Avvia ridotto a icona", "Запускать свёрнутым", "最小化して起動", "최소화하여 시작", "启动时最小化"),
"Start SharpShot with Windows (minimized)": ("Iniciar SharpShot con Windows (minimizado)", "Démarrer SharpShot avec Windows (réduit)", "SharpShot mit Windows starten (minimiert)", "Iniciar o SharpShot com o Windows (minimizado)", "Avvia SharpShot con Windows (ridotto a icona)", "Запускать SharpShot вместе с Windows (свёрнутым)", "Windows と一緒に SharpShot を起動（最小化）", "Windows와 함께 SharpShot 시작(최소화)", "随 Windows 启动 SharpShot（最小化）"),
"Adds SharpShot to your Windows startup apps and starts it minimized to the tray when Windows starts": (
"Añade SharpShot al inicio de Windows y lo abre minimizado en la bandeja.",
"Ajoute SharpShot au démarrage de Windows et l'ouvre réduit dans la barre.",
"Fügt SharpShot zum Windows-Start hinzu und öffnet es minimiert im Infobereich.",
"Adiciona o SharpShot à inicialização do Windows e o abre minimizado na bandeja.",
"Aggiunge SharpShot all'avvio di Windows e lo apre ridotto a icona.",
"Добавляет SharpShot в автозагрузку Windows и запускает его свёрнутым в трей.",
"Windows のスタートアップに追加し、起動時はトレイに最小化します。",
"Windows 시작 프로그램에 넣고, 시작할 때 트레이로 최소화합니다.",
"将 SharpShot 加入 Windows 启动项，并在开机时最小化到托盘。",
),
"Notifications": ("Notificaciones", "Notifications", "Benachrichtigungen", "Notificações", "Notifiche", "Уведомления", "通知", "알림", "通知"),
"Disable all popup notifications": ("Desactivar todas las notificaciones emergentes", "Désactiver toutes les notifications", "Alle Popup-Benachrichtigungen deaktivieren", "Desativar todas as notificações", "Disattiva tutte le notifiche", "Отключить все всплывающие уведомления", "ポップアップ通知をすべてオフにする", "모든 팝업 알림 끄기", "关闭所有弹出通知"),
"When enabled, all popup dialogs (success messages, file saved confirmations, etc.) will be suppressed": (
"Si está activo, se ocultan los cuadros emergentes (mensajes de éxito, confirmaciones de archivo guardado, etc.).",
"Si activé, les fenêtres (succès, fichier enregistré, etc.) sont masquées.",
"Wenn aktiv, werden Popup-Dialoge (Erfolg, Datei gespeichert usw.) unterdrückt.",
"Se ativado, as caixas (sucesso, arquivo salvo etc.) são ocultadas.",
"Se attivo, le finestre (successo, file salvato, ecc.) vengono nascoste.",
"Если включено, всплывающие окна (успех, файл сохранён и т. д.) не показываются.",
"オンにすると、成功メッセージや保存確認などのポップアップを出しません。",
"켜면 성공 메시지, 파일 저장 확인 같은 팝업을 표시하지 않습니다.",
"启用后，成功提示、文件已保存等弹窗都不会出现。",
),
"Screen capture": ("Captura de pantalla", "Capture d'écran", "Bildschirmaufnahme", "Captura de tela", "Cattura schermo", "Захват экрана", "画面キャプチャ", "화면 캡처", "屏幕截图"),
"Full-Screen Capture Target:": ("Destino de captura a pantalla completa:", "Cible de capture plein écran :", "Ziel der Vollbildaufnahme:", "Destino da captura em tela cheia:", "Destinazione acquisizione a schermo intero:", "Цель полноэкранного снимка:", "全画面キャプチャの対象:", "전체 화면 캡처 대상:", "全屏截图目标："),
"All Screens": ("Todas las pantallas", "Tous les écrans", "Alle Bildschirme", "Todas as telas", "Tutti gli schermi", "Все экраны", "すべての画面", "모든 화면", "所有屏幕"),
"Primary Monitor": ("Monitor principal", "Écran principal", "Hauptmonitor", "Monitor principal", "Monitor principale", "Основной монитор", "メイン モニター", "주 모니터", "主显示器"),
"Monitor 1": ("Monitor 1", "Écran 1", "Monitor 1", "Monitor 1", "Monitor 1", "Монитор 1", "モニター 1", "모니터 1", "显示器 1"),
"Monitor 2": ("Monitor 2", "Écran 2", "Monitor 2", "Monitor 2", "Monitor 2", "Монитор 2", "モニター 2", "모니터 2", "显示器 2"),
"Monitor 3": ("Monitor 3", "Écran 3", "Monitor 3", "Monitor 3", "Monitor 3", "Монитор 3", "モニター 3", "모니터 3", "显示器 3"),
"Monitor 4": ("Monitor 4", "Écran 4", "Monitor 4", "Monitor 4", "Monitor 4", "Монитор 4", "モニター 4", "모니터 4", "显示器 4"),
"Use GPU capture (DXGI) for faster screenshots": ("Usar captura por GPU (DXGI) para capturas más rápidas", "Utiliser la capture GPU (DXGI) pour des captures plus rapides", "GPU-Aufnahme (DXGI) für schnellere Screenshots", "Usar captura por GPU (DXGI) para capturas mais rápidas", "Usa acquisizione GPU (DXGI) per screenshot più rapidi", "Использовать захват GPU (DXGI) для более быстрых снимков", "GPU キャプチャ (DXGI) で高速に撮る", "더 빠른 스크린샷을 위해 GPU 캡처(DXGI) 사용", "使用 GPU 截图 (DXGI) 以加快截图"),
"Uses DXGI Desktop Duplication for region freeze-frames and fullscreen stills. Falls back to GDI if GPU capture fails. Leave off if you see blank images.": (
"Usa DXGI Desktop Duplication para el marco congelado de la región y las capturas a pantalla completa. Si falla la GPU, usa GDI. Déjalo desactivado si ves imágenes en blanco.",
"Utilise DXGI Desktop Duplication pour le cadre figé et les captures plein écran. Revient au GDI si le GPU échoue. Laissez désactivé si les images sont vides.",
"Nutzt DXGI Desktop Duplication für eingefrorene Bereiche und Vollbilder. Fällt auf GDI zurück, wenn die GPU-Aufnahme fehlschlägt. Aus lassen, wenn Bilder leer sind.",
"Usa DXGI Desktop Duplication para o quadro congelado da região e capturas em tela cheia. Se a GPU falhar, usa GDI. Deixe desativado se as imagens ficarem em branco.",
"Usa DXGI Desktop Duplication per il fotogramma fermo e le catture a schermo intero. Se la GPU fallisce, usa GDI. Lascialo disattivato se le immagini sono vuote.",
"Использует DXGI Desktop Duplication для замороженного кадра области и полноэкранных снимков. Если GPU не справляется, используется GDI. Выключите, если изображения пустые.",
"領域の静止画と全画面には DXGI Desktop Duplication を使います。GPU が失敗すると GDI に戻ります。真っ白な画像になるときはオフにしてください。",
"영역 정지 화면과 전체 화면에는 DXGI Desktop Duplication을 씁니다. GPU가 실패하면 GDI로 돌아갑니다. 이미지가 비면 끄세요.",
"区域冻结画面和全屏截图使用 DXGI Desktop Duplication。GPU 失败时回退到 GDI。如果出现空白图像，请关闭。",
),
"After capture": ("Después de capturar", "Après la capture", "Nach der Aufnahme", "Depois da captura", "Dopo l'acquisizione", "После захвата", "キャプチャ後", "캡처 후", "截图之后"),
"Auto-copy fullscreen and region screenshots to clipboard (failsafe after editor closes)": (
"Copiar automáticamente las capturas de pantalla completa y de región al portapapeles (respaldo al cerrar el editor)",
"Copier automatiquement les captures plein écran et de région dans le presse-papiers (secours à la fermeture de l'éditeur)",
"Vollbild- und Bereichsscreenshots automatisch in die Zwischenablage kopieren (Fallback nach Schließen des Editors)",
"Copiar automaticamente capturas de tela cheia e de região para a área de transferência (reserva ao fechar o editor)",
"Copia automaticamente screenshot a schermo intero e di regione negli appunti (riserva alla chiusura dell'editor)",
"Автоматически копировать полноэкранные снимки и снимки области в буфер (запасной вариант после закрытия редактора)",
"全画面と領域のスクリーンショットを自動でクリップボードにコピー（エディターを閉じた後の予備）",
"전체 화면과 영역 스크린샷을 자동으로 클립보드에 복사(편집기를 닫은 뒤의 안전장치)",
"自动将全屏和区域截图复制到剪贴板（编辑器关闭后的补救）",
),
"Automatically copies screenshots to clipboard after the editor closes, as a failsafe if you didn't copy in the editor. Applies to both fullscreen and region screenshots.": (
"Copia la captura al portapapeles al cerrar el editor, por si no la copiaste dentro. Sirve para pantalla completa y región.",
"Copie la capture dans le presse-papiers à la fermeture de l'éditeur, si vous ne l'avez pas copiée dedans. Plein écran et région.",
"Kopiert den Screenshot nach dem Schließen des Editors in die Zwischenablage, falls Sie ihn dort nicht kopiert haben. Gilt für Vollbild und Bereich.",
"Copia a captura para a área de transferência ao fechar o editor, se você não copiou dentro dele. Vale para tela cheia e região.",
"Copia lo screenshot negli appunti alla chiusura dell'editor, se non l'hai copiato lì. Vale per schermo intero e regione.",
"Копирует снимок в буфер после закрытия редактора, если вы не скопировали его там. Для полного экрана и области.",
"エディターでコピーしなかった場合に備え、閉じたあとクリップボードへコピーします。全画面と領域の両方です。",
"편집기에서 복사하지 않았을 때를 대비해, 닫은 뒤 클립보드에 복사합니다. 전체 화면과 영역 모두입니다.",
"如果在编辑器里没有复制，关闭后会把截图复制到剪贴板。全屏和区域都适用。",
),
"Skip editor and auto-copy for region screenshots": ("Omitir el editor y copiar automáticamente las capturas de región", "Ignorer l'éditeur et copier automatiquement les captures de région", "Editor überspringen und Bereichsscreenshots automatisch kopieren", "Pular o editor e copiar automaticamente capturas de região", "Salta l'editor e copia automaticamente le catture di regione", "Пропустить редактор и сразу копировать снимки области", "領域キャプチャはエディターを飛ばして自動コピー", "영역 스크린샷은 편집기를 건너뛰고 자동 복사", "区域截图跳过编辑器并自动复制"),
"When enabled, region screenshots will skip the editor overlay and automatically copy to clipboard for immediate pasting": (
"Si está activo, las capturas de región no abren el editor y se copian al portapapeles para pegarlas al momento.",
"Si activé, les captures de région n'ouvrent pas l'éditeur et vont dans le presse-papiers pour un collage immédiat.",
"Wenn aktiv, überspringen Bereichsscreenshots den Editor und landen in der Zwischenablage zum sofortigen Einfügen.",
"Se ativado, capturas de região não abrem o editor e vão para a área de transferência para colar na hora.",
"Se attivo, le catture di regione saltano l'editor e vanno negli appunti per incollarle subito.",
"Если включено, снимки области не открывают редактор и сразу копируются в буфер для вставки.",
"オンにすると領域キャプチャはエディターを開かず、すぐ貼れるようクリップボードへコピーします。",
"켜면 영역 스크린샷은 편집기를 열지 않고 바로 붙여넣을 수 있게 클립보드에 복사됩니다.",
"启用后，区域截图不打开编辑器，并自动复制到剪贴板以便立即粘贴。",
),
"Adjust region before opening the editor": ("Ajustar la región antes de abrir el editor", "Ajuster la région avant d'ouvrir l'éditeur", "Bereich vor dem Editor anpassen", "Ajustar a região antes de abrir o editor", "Regola la regione prima di aprire l'editor", "Поправить область перед редактором", "エディターを開く前に領域を調整", "편집기를 열기 전에 영역 조정", "打开编辑器前调整区域"),
"Freezes all monitors, then keeps the dashed selection on screen so you can drag the edges to resize before Enter opens the editor (or copies, if skip-editor is on). Esc cancels.": (
"Congela todos los monitores y deja la selección punteada para que arrastres los bordes antes de que Enter abra el editor (o copie, si se omite el editor). Esc cancela.",
"Fige tous les écrans, puis garde la sélection en pointillés pour redimensionner les bords avant qu'Entrée n'ouvre l'éditeur (ou ne copie, si l'éditeur est ignoré). Échap annule.",
"Friert alle Monitore ein und lässt die gestrichelte Auswahl stehen, damit Sie die Kanten ziehen können, bevor die Eingabetaste den Editor öffnet (oder kopiert, wenn der Editor übersprungen wird). Esc bricht ab.",
"Congela todos os monitores e mantém a seleção tracejada para arrastar as bordas antes de Enter abrir o editor (ou copiar, se o editor for pulado). Esc cancela.",
"Congela tutti i monitor e lascia la selezione tratteggiata per trascinare i bordi prima che Invio apra l'editor (o copi, se l'editor è saltato). Esc annulla.",
"Замораживает все мониторы и оставляет пунктирное выделение, чтобы потянуть края до Enter. Enter открывает редактор (или копирует, если редактор пропущен). Esc отменяет.",
"すべてのモニターを静止させ、破線の選択を残します。Enter でエディターを開く（エディター省略時はコピー）前に端をドラッグできます。Esc でキャンセル。",
"모든 모니터를 멈춘 뒤 점선 선택을 남겨 둡니다. Enter로 편집기를 열기(편집기 생략 시 복사) 전에 가장자리를 드래그할 수 있습니다. Esc는 취소입니다.",
"冻结所有显示器，并保留虚线选区，以便在按 Enter 打开编辑器（若跳过编辑器则复制）之前拖动边缘调整大小。Esc 取消。",
),
"Show OCR quick-capture button on dashboard": ("Mostrar el botón de captura rápida OCR en el panel", "Afficher le bouton de capture OCR rapide sur le tableau de bord", "OCR-Schnellaufnahme auf der Übersicht anzeigen", "Mostrar o botão de captura rápida de OCR no painel", "Mostra il pulsante di acquisizione OCR rapida sul pannello", "Показывать кнопку быстрого OCR на панели", "ダッシュボードに OCR クイックキャプチャを表示", "대시보드에 OCR 빠른 캡처 버튼 표시", "在仪表盘显示 OCR 快速截图按钮"),
"Adds an OCR button to the main dashboard. Click it to region-select and extract text directly without opening the screenshot editor.": (
"Añade un botón OCR al panel principal. Al pulsarlo eliges una región y extrae el texto sin abrir el editor.",
"Ajoute un bouton OCR au tableau de bord. Cliquez pour sélectionner une région et extraire le texte sans ouvrir l'éditeur.",
"Fügt der Übersicht eine OCR-Schaltfläche hinzu. Damit wählen Sie einen Bereich und lesen Text aus, ohne den Editor zu öffnen.",
"Adiciona um botão de OCR ao painel. Clique para selecionar uma região e extrair o texto sem abrir o editor.",
"Aggiunge un pulsante OCR al pannello. Cliccalo per selezionare una regione ed estrarre il testo senza aprire l'editor.",
"Добавляет кнопку OCR на панель. Нажмите, чтобы выделить область и извлечь текст без редактора.",
"メインのダッシュボードに OCR ボタンを追加します。押すと領域を選んで、エディターを開かず文字を取り出します。",
"메인 대시보드에 OCR 버튼을 넣습니다. 누르면 영역을 선택해 편집기를 열지 않고 글을 추출합니다.",
"在主仪表盘添加 OCR 按钮。点击后框选区域并直接提取文字，不打开截图编辑器。",
),
"Show Smart Regions toggle on dashboard (beta)": ("Mostrar el interruptor de regiones inteligentes en el panel (beta)", "Afficher le bouton Régions intelligentes sur le tableau de bord (bêta)", "Smart-Regionen-Schalter auf der Übersicht anzeigen (Beta)", "Mostrar o botão de regiões inteligentes no painel (beta)", "Mostra l'interruttore Regioni intelligenti sul pannello (beta)", "Показывать переключатель умных областей на панели (бета)", "ダッシュボードにスマート領域スイッチを表示（ベータ）", "대시보드에 스마트 영역 전환 표시(베타)", "在仪表盘显示智能区域开关（测试版）"),
"Adds a Smart toggle to the dashboard. When on, SharpShot highlights content regions on the active window so you can click to copy text.": (
"Añade un interruptor Smart al panel. Encendido, SharpShot resalta regiones de contenido en la ventana activa para copiar el texto al hacer clic.",
"Ajoute un bouton Smart au tableau de bord. Activé, SharpShot surligne les zones de contenu de la fenêtre active pour copier le texte d'un clic.",
"Fügt der Übersicht einen Smart-Schalter hinzu. Wenn an, hebt SharpShot Inhaltsbereiche im aktiven Fenster hervor, damit Sie Text per Klick kopieren.",
"Adiciona um botão Smart ao painel. Ligado, o SharpShot destaca regiões de conteúdo na janela ativa para copiar o texto com um clique.",
"Aggiunge un interruttore Smart al pannello. Se acceso, SharpShot evidenzia le regioni di contenuto nella finestra attiva per copiare il testo con un clic.",
"Добавляет переключатель Smart на панель. Когда он включён, SharpShot подсвечивает области содержимого в активном окне, чтобы скопировать текст щелчком.",
"ダッシュボードに Smart スイッチを追加します。オンのとき、アクティブなウィンドウの内容を強調表示し、クリックで文字をコピーできます。",
"대시보드에 Smart 스위치를 추가합니다. 켜면 활성 창의 내용 영역을 강조해 클릭하면 글을 복사할 수 있습니다.",
"在仪表盘添加 Smart 开关。打开后，SharpShot 会标出当前窗口中的内容区域，点击即可复制文字。",
),
"Use dense OCR for Smart Regions (more text, slower) (beta)": ("Usar OCR denso para regiones inteligentes (más texto, más lento) (beta)", "Utiliser un OCR dense pour les régions intelligentes (plus de texte, plus lent) (bêta)", "Dichte OCR für Smart-Regionen (mehr Text, langsamer) (Beta)", "Usar OCR denso para regiões inteligentes (mais texto, mais lento) (beta)", "Usa OCR denso per le regioni intelligenti (più testo, più lento) (beta)", "Плотный OCR для умных областей (больше текста, медленнее) (бета)", "スマート領域に密な OCR を使う（文字は増えるが遅い）（ベータ）", "스마트 영역에 촘촘한 OCR 사용(글은 더 많고 느림)(베타)", "智能区域使用密集 OCR（文字更多，更慢）（测试版）"),
"Runs overlapping tiled OCR (SparseText + Auto) so Smart Regions find more on-screen text in browsers, games, and Electron apps. Turn off for a faster but thinner pass.": (
"Ejecuta un OCR en mosaicos solapados (SparseText + Auto) para encontrar más texto en navegadores, juegos y apps Electron. Desactívalo para un pase más rápido y menos completo.",
"Lance un OCR en tuiles qui se chevauchent (SparseText + Auto) pour trouver plus de texte dans les navigateurs, jeux et apps Electron. Désactivez pour un passage plus rapide mais plus mince.",
"Führt überlappendes Kachel-OCR aus (SparseText + Auto), damit Smart-Regionen mehr Text in Browsern, Spielen und Electron-Apps finden. Aus schalten für einen schnelleren, dünneren Durchlauf.",
"Executa OCR em blocos sobrepostos (SparseText + Auto) para achar mais texto em navegadores, jogos e apps Electron. Desative para um passe mais rápido e mais raso.",
"Esegue OCR a riquadri sovrapposti (SparseText + Auto) per trovare più testo in browser, giochi e app Electron. Disattivalo per un passaggio più rapido ma più scarso.",
"Запускает перекрывающийся тайловый OCR (SparseText + Auto), чтобы умные области находили больше текста в браузерах, играх и приложениях Electron. Выключите для более быстрого, но более бедного прохода.",
"重なるタイル OCR（SparseText + Auto）で、ブラウザー、ゲーム、Electron アプリの文字をより多く見つけます。オフにすると速くなりますが拾う量は減ります。",
"겹치는 타일 OCR(SparseText + Auto)로 브라우저, 게임, Electron 앱의 글을 더 찾습니다. 끄면 더 빠르지만 덜 잡습니다.",
"运行重叠分块 OCR（SparseText + Auto），让智能区域在浏览器、游戏和 Electron 应用中找到更多文字。关闭后更快，但识别更少。",
),
"Group Smart Region text (beta)": ("Agrupar el texto de regiones inteligentes (beta)", "Regrouper le texte des régions intelligentes (bêta)", "Smart-Region-Text gruppieren (Beta)", "Agrupar o texto das regiões inteligentes (beta)", "Raggruppa il testo delle regioni intelligenti (beta)", "Группировать текст умных областей (бета)", "スマート領域の文字をまとめる（ベータ）", "스마트 영역 글 묶기(베타)", "分组智能区域文字（测试版）"),
"Line": ("Línea", "Ligne", "Zeile", "Linha", "Riga", "Строка", "行", "줄", "行"),
"Line: one box per row. Paragraph: join tight lines. Multiple paragraphs: join neighboring paragraphs.": (
"Línea: una caja por fila. Párrafo: une líneas cercanas. Varios párrafos: une párrafos vecinos.",
"Ligne : une boîte par rangée. Paragraphe : relie les lignes serrées. Plusieurs paragraphes : relie les paragraphes voisins.",
"Zeile: ein Kasten pro Zeile. Absatz: enge Zeilen verbinden. Mehrere Absätze: benachbarte Absätze verbinden.",
"Linha: uma caixa por linha. Parágrafo: junta linhas próximas. Vários parágrafos: junta parágrafos vizinhos.",
"Riga: una casella per riga. Paragrafo: unisce righe vicine. Più paragrafi: unisce paragrafi vicini.",
"Строка: одна рамка на ряд. Абзац: склеивает близкие строки. Несколько абзацев: склеивает соседние абзацы.",
"行: 1 行につき 1 つの枠。段落: 近い行を結合。複数の段落: 隣り合う段落を結合。",
"줄: 한 줄에 상자 하나. 문단: 가까운 줄을 합침. 여러 문단: 이웃한 문단을 합침.",
"行：每行一个框。段落：合并紧挨的行。多个段落：合并相邻段落。",
),
"Paragraph": ("Párrafo", "Paragraphe", "Absatz", "Parágrafo", "Paragrafo", "Абзац", "段落", "문단", "段落"),
"Multiple paragraphs": ("Varios párrafos", "Plusieurs paragraphes", "Mehrere Absätze", "Vários parágrafos", "Più paragrafi", "Несколько абзацев", "複数の段落", "여러 문단", "多个段落"),
"Horizontal gap before split (beta)": ("Hueco horizontal antes de dividir (beta)", "Écart horizontal avant séparation (bêta)", "Waagerechte Lücke vor dem Teilen (Beta)", "Espaço horizontal antes de dividir (beta)", "Spazio orizzontale prima della divisione (beta)", "Горизонтальный зазор перед разделением (бета)", "分割する前の横のすき間（ベータ）", "나누기 전 가로 간격(베타)", "拆分前的水平间距（测试版）"),
"Widest": ("El más ancho", "Le plus large", "Am weitesten", "O mais largo", "Il più largo", "Самый широкий", "最も広い", "가장 넓음", "最宽"),
"Splits a line only when neighboring words have a hole much larger than the sentence's own spacing. Off never splits. Widest is the smallest split. Close splits on smaller gaps.": (
"Divide una línea solo si el hueco entre palabras es mucho mayor que el espaciado de la frase. Desactivado nunca divide. El más ancho es el corte más pequeño. Cercano divide huecos menores.",
"Ne sépare une ligne que si le trou entre les mots est bien plus grand que l'espacement de la phrase. Désactivé ne sépare jamais. Le plus large est la plus petite coupe. Proche sépare de plus petits écarts.",
"Teilt eine Zeile nur, wenn die Lücke zwischen Wörtern viel größer ist als der Satzabstand. Aus teilt nie. Am weitesten ist der kleinste Schnitt. Eng teilt bei kleineren Lücken.",
"Divide uma linha só quando o buraco entre palavras é bem maior que o espaçamento da frase. Desligado nunca divide. O mais largo é o menor corte. Perto divide buracos menores.",
"Divide una riga solo se il buco tra le parole è molto più grande della spaziatura della frase. Disattivato non divide mai. Il più largo è il taglio più piccolo. Vicino divide spazi più piccoli.",
"Делит строку только если дыра между словами намного больше промежутка в самой фразе. Выкл. никогда не делит. Самый широкий — самый маленький разрез. Близко делит меньшие зазоры.",
"隣の語のすき間が文の字間よりかなり大きいときだけ行を分けます。オフは分けません。最も広いが一番小さな分割です。近いほど小さいすき間で分けます。",
"이웃 단어 사이 구멍이 문장 간격보다 훨씬 클 때만 줄을 나눕니다. 끄면 나누지 않습니다. 가장 넓음이 가장 작은 분할입니다. 가까움은 더 작은 간격에서 나눕니다.",
"只有相邻词之间的空隙远大于句子本身的间距时才拆行。关闭则从不拆分。最宽是最小的拆分。较近会在更小的空隙处拆分。",
),
"Off": ("Desactivado", "Désactivé", "Aus", "Desligado", "Disattivato", "Выкл.", "オフ", "끄기", "关闭"),
"Wide": ("Ancho", "Large", "Weit", "Largo", "Largo", "Широко", "広い", "넓음", "宽"),
"Close gaps": ("Cercano", "Proche", "Eng", "Perto", "Vicino", "Близко", "近い", "가까움", "较近"),
"Far apart": ("Muy separados", "Très écartés", "Weit auseinander", "Bem separados", "Molto distanti", "Далеко друг от друга", "かなり離れている", "멀리 떨어짐", "相距很远"),
"Skip post-capture menu for screenshots and videos": ("Omitir el menú posterior en capturas y vídeos", "Ignorer le menu après capture pour images et vidéos", "Menü nach Aufnahme für Bilder und Videos überspringen", "Pular o menu após captura de imagens e vídeos", "Salta il menu dopo acquisizione per immagini e video", "Пропускать меню после снимков и видео", "画像と動画のキャプチャ後メニューを省略", "스크린샷과 동영상의 캡처 후 메뉴 건너뛰기", "截图和视频跳过捕获后菜单"),
"When enabled, SharpShot skips the copy/save/cancel dashboard menu after region, fullscreen, and video captures.": (
"Si está activo, SharpShot no muestra el menú de copiar, guardar o cancelar tras una región, pantalla completa o vídeo.",
"Si activé, SharpShot n'affiche pas le menu copier/enregistrer/annuler après une région, un plein écran ou une vidéo.",
"Wenn aktiv, zeigt SharpShot nach Bereich, Vollbild und Video nicht das Menü Kopieren/Speichern/Abbrechen.",
"Se ativado, o SharpShot não mostra o menu copiar/salvar/cancelar depois de região, tela cheia ou vídeo.",
"Se attivo, SharpShot non mostra il menu copia/salva/annulla dopo regione, schermo intero o video.",
"Если включено, SharpShot не показывает меню копирования, сохранения и отмены после области, полного экрана и видео.",
"オンにすると、領域・全画面・動画のあとでコピー/保存/キャンセルのメニューを出しません。",
"켜면 영역, 전체 화면, 동영상 뒤에 복사/저장/취소 메뉴를 띄우지 않습니다.",
"启用后，区域、全屏和视频捕获完成后不再显示复制/保存/取消菜单。",
),
"Hide SharpShot windows in screenshots (dashboard, editor, magnifier)": ("Ocultar las ventanas de SharpShot en las capturas (panel, editor, lupa)", "Masquer les fenêtres SharpShot dans les captures (tableau de bord, éditeur, loupe)", "SharpShot-Fenster in Screenshots ausblenden (Übersicht, Editor, Lupe)", "Ocultar janelas do SharpShot nas capturas (painel, editor, lupa)", "Nascondi le finestre di SharpShot negli screenshot (pannello, editor, lente)", "Скрывать окна SharpShot на снимках (панель, редактор, лупа)", "スクリーンショットで SharpShot の窓を隠す（ダッシュボード、エディター、拡大鏡）", "스크린샷에서 SharpShot 창 숨기기(대시보드, 편집기, 돋보기)", "截图中隐藏 SharpShot 窗口（仪表盘、编辑器、放大镜）"),
"When enabled, SharpShot temporarily hides its own windows while the screen pixels are captured so they do not appear in the image. In the editor, the bottom toolbar, color panel, and OCR popup are hidden briefly when you save or copy so they are not baked into the file.": (
"Si está activo, SharpShot oculta un momento sus ventanas al capturar los píxeles para que no salgan en la imagen. En el editor, la barra inferior, el panel de color y el aviso de OCR se ocultan al guardar o copiar para no quedar en el archivo.",
"Si activé, SharpShot masque brièvement ses fenêtres pendant la capture des pixels pour qu'elles n'apparaissent pas. Dans l'éditeur, la barre du bas, le panneau de couleur et la fenêtre OCR sont masqués à l'enregistrement ou à la copie.",
"Wenn aktiv, blendet SharpShot seine Fenster kurz aus, während die Pixel erfasst werden, damit sie nicht im Bild sind. Im Editor werden untere Leiste, Farbfeld und OCR-Fenster beim Speichern oder Kopieren kurz ausgeblendet.",
"Se ativado, o SharpShot oculta por um instante as próprias janelas enquanto os pixels são capturados. No editor, a barra inferior, o painel de cor e o aviso de OCR somem ao salvar ou copiar para não irem para o arquivo.",
"Se attivo, SharpShot nasconde per un attimo le proprie finestre mentre cattura i pixel. Nell'editor, la barra in basso, il pannello colore e il popup OCR spariscono al salvataggio o alla copia.",
"Если включено, SharpShot на мгновение скрывает свои окна при захвате пикселей, чтобы их не было на снимке. В редакторе нижняя панель, панель цвета и окно OCR скрываются при сохранении или копировании.",
"オンにすると、画面のピクセルを取るあいだ自前の窓を一時的に隠します。エディターでは保存やコピーのとき下のツールバー、色パネル、OCR ポップアップを一瞬隠し、ファイルに焼き付かないようにします。",
"켜면 화면 픽셀을 찍는 동안 자기 창을 잠시 숨깁니다. 편집기에서는 저장이나 복사할 때 아래 도구 모음, 색 패널, OCR 팝업을 잠깐 숨겨 파일에 남지 않게 합니다.",
"启用后，抓取屏幕像素时会暂时隐藏 SharpShot 自己的窗口，避免出现在图像里。在编辑器中保存或复制时，底部工具栏、颜色面板和 OCR 弹窗也会短暂隐藏，以免被写进文件。",
),
"Magnifier": ("Lupa", "Loupe", "Lupe", "Lupa", "Lente", "Лупа", "拡大鏡", "돋보기", "放大镜"),
"Enable magnifier during region selection": ("Activar la lupa al seleccionar la región", "Activer la loupe pendant la sélection de région", "Lupe bei der Bereichsauswahl aktivieren", "Ativar a lupa ao selecionar a região", "Attiva la lente durante la selezione della regione", "Включить лупу при выборе области", "領域選択中に拡大鏡を使う", "영역 선택 중 돋보기 사용", "选择区域时启用放大镜"),
"Magnifier Zoom Level:": ("Aumento de la lupa:", "Niveau de zoom de la loupe :", "Lupenvergrößerung:", "Nível de zoom da lupa:", "Ingrandimento della lente:", "Увеличение лупы:", "拡大鏡の倍率:", "돋보기 배율:", "放大镜缩放："),
"Magnifier Size (Stationary):": ("Tamaño de la lupa (fija):", "Taille de la loupe (fixe) :", "Lupengröße (fest):", "Tamanho da lupa (fixa):", "Dimensione lente (fissa):", "Размер лупы (неподвижная):", "拡大鏡のサイズ（固定）:", "돋보기 크기(고정):", "放大镜大小（固定）："),
"Magnifier Size (Follow/Auto):": ("Tamaño de la lupa (seguir/auto):", "Taille de la loupe (suivre/auto) :", "Lupengröße (Folgen/Auto):", "Tamanho da lupa (seguir/auto):", "Dimensione lente (segui/auto):", "Размер лупы (следовать/авто):", "拡大鏡のサイズ（追従/自動）:", "돋보기 크기(따라가기/자동):", "放大镜大小（跟随/自动）："),
"Magnifier Mode:": ("Modo de la lupa:", "Mode de la loupe :", "Lupenmodus:", "Modo da lupa:", "Modalità lente:", "Режим лупы:", "拡大鏡のモード:", "돋보기 모드:", "放大镜模式："),
"Follow Cursor": ("Seguir el cursor", "Suivre le curseur", "Cursor folgen", "Seguir o cursor", "Segui il cursore", "Следовать за курсором", "カーソルに追従", "커서 따라가기", "跟随光标"),
"Stationary": ("Fija", "Fixe", "Fest", "Fixa", "Fissa", "Неподвижная", "固定", "고정", "固定"),
"Auto (Stationary on non-100% monitors)": ("Auto (fija en monitores que no están al 100%)", "Auto (fixe sur les écrans pas à 100 %)", "Auto (fest auf Monitoren nicht bei 100 %)", "Auto (fixa em monitores que não estão em 100%)", "Auto (fissa sui monitor non al 100%)", "Авто (неподвижная на мониторах не 100%)", "自動（100% 以外のモニターでは固定）", "자동(100%가 아닌 모니터에서는 고정)", "自动（非 100% 缩放的显示器上固定）"),
"Stationary Magnifier Settings:": ("Ajustes de la lupa fija:", "Paramètres de la loupe fixe :", "Einstellungen der festen Lupe:", "Configurações da lupa fixa:", "Impostazioni lente fissa:", "Параметры неподвижной лупы:", "固定拡大鏡の設定:", "고정 돋보기 설정:", "固定放大镜设置："),
"Monitor:": ("Monitor:", "Écran :", "Monitor:", "Monitor:", "Monitor:", "Монитор:", "モニター:", "모니터:", "显示器："),
"Position X (%):": ("Posición X (%):", "Position X (%) :", "Position X (%):", "Posição X (%):", "Posizione X (%):", "Позиция X (%):", "位置 X (%):", "위치 X(%):", "位置 X（%）："),
"Position Y (%):": ("Posición Y (%):", "Position Y (%) :", "Position Y (%):", "Posição Y (%):", "Posizione Y (%):", "Позиция Y (%):", "位置 Y (%):", "위치 Y(%):", "位置 Y（%）："),
"Position is relative to the selected monitor (0% = top/left, 100% = bottom/right)": (
"La posición es relativa al monitor elegido (0% = arriba/izquierda, 100% = abajo/derecha).",
"La position est relative à l'écran choisi (0 % = haut/gauche, 100 % = bas/droite).",
"Die Position bezieht sich auf den gewählten Monitor (0 % = oben/links, 100 % = unten/rechts).",
"A posição é relativa ao monitor escolhido (0% = topo/esquerda, 100% = base/direita).",
"La posizione è relativa al monitor scelto (0% = alto/sinistra, 100% = basso/destra).",
"Позиция относительно выбранного монитора (0% = верх/лево, 100% = низ/право).",
"位置は選んだモニターに対する割合です（0% = 上/左、100% = 下/右）。",
"위치는 선택한 모니터 기준입니다(0% = 위/왼쪽, 100% = 아래/오른쪽).",
"位置相对于所选显示器（0% = 上/左，100% = 下/右）。",
),
"Advanced magnifier (auto mode & boundary boxes)": ("Lupa avanzada (modo automático y cajas de límite)", "Loupe avancée (mode auto et cadres de limite)", "Erweiterte Lupe (Automodus und Grenzrahmen)", "Lupa avançada (modo automático e caixas de limite)", "Lente avanzata (modo automatico e riquadri di confine)", "Расширенная лупа (авторежим и рамки границ)", "詳細な拡大鏡（自動モードと境界ボックス）", "고급 돋보기(자동 모드 및 경계 상자)", "高级放大镜（自动模式和边界框）"),
"Select monitors that should use stationary mode:": ("Elige los monitores que deben usar el modo fijo:", "Choisissez les écrans qui doivent utiliser le mode fixe :", "Monitore wählen, die den festen Modus nutzen sollen:", "Escolha os monitores que devem usar o modo fixo:", "Scegli i monitor che devono usare la modalità fissa:", "Выберите мониторы для неподвижного режима:", "固定モードにするモニターを選んでください:", "고정 모드를 쓸 모니터를 선택하세요:", "选择应使用固定模式的显示器："),
"Checked monitors will automatically switch to stationary mode when your cursor enters them. Unchecked monitors will use follow cursor mode.": (
"Los monitores marcados pasan a modo fijo cuando el cursor entra. Los no marcados siguen el cursor.",
"Les écrans cochés passent en mode fixe quand le curseur y entre. Les autres suivent le curseur.",
"Aktivierte Monitore wechseln in den festen Modus, wenn der Cursor sie betritt. Andere folgen dem Cursor.",
"Os monitores marcados passam para o modo fixo quando o cursor entra. Os desmarcados seguem o cursor.",
"I monitor selezionati passano alla modalità fissa quando il cursore entra. Gli altri seguono il cursore.",
"Отмеченные мониторы переключаются в неподвижный режим, когда курсор на них попадает. Остальные следуют за курсором.",
"チェックしたモニターはカーソルが入ると固定モードになります。外したものはカーソル追従です。",
"선택한 모니터는 커서가 들어가면 고정 모드로 바뀝니다. 선택하지 않은 모니터는 커서를 따라갑니다.",
"勾选的显示器在光标进入时自动改为固定模式。未勾选的显示器跟随光标。",
),
"Boundary Boxes (for DPI-scaled monitors):": ("Cajas de límite (monitores con escala DPI):", "Cadres de limite (écrans avec mise à l'échelle DPI) :", "Grenzrahmen (für DPI-skalierte Monitore):", "Caixas de limite (monitores com escala de DPI):", "Riquadri di confine (monitor con scala DPI):", "Рамки границ (мониторы с масштабом DPI):", "境界ボックス（DPI 拡大のモニター用）:", "경계 상자(DPI 배율 모니터용):", "边界框（用于 DPI 缩放的显示器）："),
"If monitor detection doesn't work correctly (especially on any monitor that is not on 100% scaled zoom), you can draw custom boundary boxes. Checked boxes will trigger stationary mode when your cursor enters them. You can have multiple boxes per monitor.": (
"Si la detección del monitor falla (sobre todo si no está al 100%), puedes dibujar cajas de límite. Las marcadas activan el modo fijo al entrar el cursor. Puedes tener varias por monitor.",
"Si la détection d'écran échoue (surtout hors 100 %), vous pouvez dessiner des cadres. Les cadres cochés passent en mode fixe quand le curseur y entre. Plusieurs cadres par écran sont possibles.",
"Wenn die Monitorerkennung nicht stimmt (vor allem nicht bei 100 %), können Sie Grenzrahmen zeichnen. Aktivierte Rahmen schalten den festen Modus ein, wenn der Cursor sie betritt. Mehrere Rahmen pro Monitor sind möglich.",
"Se a detecção do monitor falhar (sobretudo fora de 100%), você pode desenhar caixas de limite. As marcadas ativam o modo fixo quando o cursor entra. Pode haver várias por monitor.",
"Se il rilevamento del monitor non funziona (soprattutto se non è al 100%), puoi disegnare riquadri. Quelli selezionati attivano la modalità fissa quando il cursore entra. Puoi averne più di uno per monitor.",
"Если монитор определяется неверно (особенно не при 100%), можно нарисовать рамки. Отмеченные включают неподвижный режим, когда курсор входит. На одном мониторе может быть несколько рамок.",
"モニター検出が正しくないとき（特に 100% 以外）は境界ボックスを描けます。チェックした枠にカーソルが入ると固定モードになります。モニターごとに複数置けます。",
"모니터 감지가 맞지 않으면(특히 100%가 아닐 때) 경계 상자를 그릴 수 있습니다. 선택한 상자에 커서가 들어가면 고정 모드가 됩니다. 모니터마다 여러 개를 둘 수 있습니다.",
"如果显示器识别不准（尤其不是 100% 缩放），可以手绘边界框。勾选的框在光标进入时会切换到固定模式。每个显示器可以有多个框。",
),
"Add Boundary Box": ("Añadir caja de límite", "Ajouter un cadre de limite", "Grenzrahmen hinzufügen", "Adicionar caixa de limite", "Aggiungi riquadro di confine", "Добавить рамку границы", "境界ボックスを追加", "경계 상자 추가", "添加边界框"),
"Video & audio": ("Vídeo y audio", "Vidéo et audio", "Video und Audio", "Vídeo e áudio", "Video e audio", "Видео и звук", "映像と音声", "영상 및 오디오", "视频和音频"),
"Video Quality:": ("Calidad de vídeo:", "Qualité vidéo :", "Videoqualität:", "Qualidade do vídeo:", "Qualità video:", "Качество видео:", "映像の品質:", "영상 품질:", "视频质量："),
"High": ("Alta", "Élevée", "Hoch", "Alta", "Alta", "Высокое", "高", "높음", "高"),
"Medium": ("Media", "Moyenne", "Mittel", "Média", "Media", "Среднее", "中", "보통", "中"),
"Low": ("Baja", "Faible", "Niedrig", "Baixa", "Bassa", "Низкое", "低", "낮음", "低"),
"Screen recordings use FFmpeg.": ("Las grabaciones de pantalla usan FFmpeg.", "Les enregistrements d'écran utilisent FFmpeg.", "Bildschirmaufnahmen nutzen FFmpeg.", "As gravações de tela usam o FFmpeg.", "Le registrazioni dello schermo usano FFmpeg.", "Запись экрана использует FFmpeg.", "画面録画には FFmpeg を使います。", "화면 녹화는 FFmpeg를 사용합니다.", "屏幕录制使用 FFmpeg。"),
"Your own recorder": ("Tu propia grabadora", "Votre propre enregistreur", "Dein eigenes Aufnahmeprogramm", "Seu próprio gravador", "Il tuo registratore", "Ваша программа записи", "自分の録画アプリ", "내가 쓰는 녹화 프로그램", "你自己的录制程序"),
"SharpShot recordings use FFmpeg. You can also link a recorder you already installed and open it from SharpShot without leaving your flow. A more advanced app such as OBS Studio is a common choice. SharpShot does not include that app. It stays separate, with its own terms and privacy policy. Add any program from Dashboard → Linked apps. The shortcut below is only if the recorder you want is OBS Studio.": (
"Las grabaciones de SharpShot usan FFmpeg. También puedes vincular una grabadora que ya tengas e iniciarla desde SharpShot sin salir de tu flujo. Una app más avanzada, como OBS Studio, es una opción habitual. SharpShot no la incluye. Sigue siendo un programa aparte, con sus propios términos y su política de privacidad. Añade cualquier programa en Panel → Aplicaciones vinculadas. El atajo de abajo es solo si la grabadora que quieres es OBS Studio.",
"Les enregistrements SharpShot utilisent FFmpeg. Vous pouvez aussi lier un enregistreur déjà installé et l'ouvrir depuis SharpShot sans quitter votre flux. Une app plus avancée comme OBS Studio est un choix courant. SharpShot ne l'inclut pas. Elle reste séparée, avec ses propres conditions et sa politique de confidentialité. Ajoutez un programme dans Tableau de bord → Applications liées. Le raccourci ci-dessous ne sert que si l'enregistreur voulu est OBS Studio.",
"SharpShot-Aufnahmen nutzen FFmpeg. Sie können auch ein bereits installiertes Aufnahmeprogramm verknüpfen und aus SharpShot öffnen, ohne den Ablauf zu verlassen. Eine umfangreichere App wie OBS Studio ist eine übliche Wahl. SharpShot enthält sie nicht. Sie bleibt getrennt, mit eigenen Bedingungen und eigener Datenschutzrichtlinie. Fügen Sie ein Programm unter Übersicht → Verknüpfte Apps hinzu. Die Verknüpfung unten gilt nur, wenn das gewünschte Programm OBS Studio ist.",
"As gravações do SharpShot usam o FFmpeg. Você também pode vincular um gravador já instalado e abri-lo pelo SharpShot sem sair do fluxo. Um app mais avançado, como o OBS Studio, é uma escolha comum. O SharpShot não o inclui. Ele continua separado, com os próprios termos e a própria política de privacidade. Adicione qualquer programa em Painel → Aplicativos vinculados. O atalho abaixo só vale se o gravador desejado for o OBS Studio.",
"Le registrazioni di SharpShot usano FFmpeg. Puoi anche collegare un registratore già installato e aprirlo da SharpShot senza uscire dal flusso. Un'app più avanzata come OBS Studio è una scelta comune. SharpShot non la include. Resta separata, con i propri termini e la propria informativa privacy. Aggiungi un programma da Pannello → App collegate. Il collegamento sotto vale solo se il registratore che vuoi è OBS Studio.",
"Записи SharpShot используют FFmpeg. Можно также связать уже установленную программу записи и открывать её из SharpShot, не выходя из работы. Более сложное приложение, например OBS Studio, — обычный выбор. SharpShot его не включает. Оно остаётся отдельным, со своими условиями и политикой конфиденциальности. Добавьте любую программу: Панель → Связанные приложения. Ярлык ниже — только если нужная программа именно OBS Studio.",
"SharpShot の録画は FFmpeg を使います。すでに入っている録画アプリを結び、作業の流れを離れずに SharpShot から開けます。OBS Studio のような高機能アプリがよく選ばれます。SharpShot には含まれません。別のアプリのまま、独自の利用規約とプライバシー ポリシーがあります。ダッシュボード → リンクしたアプリから追加してください。下のショートカットは、使いたい録画アプリが OBS Studio のときだけです。",
"SharpShot 녹화는 FFmpeg를 사용합니다. 이미 설치한 녹화 프로그램을 연결해 흐름을 벗어나지 않고 SharpShot에서 열 수 있습니다. OBS Studio처럼 더 복잡한 앱이 흔한 선택입니다. SharpShot에 포함되어 있지 않습니다. 별도의 앱으로 남고, 자체 약관과 개인정보 처리방침이 있습니다. 대시보드 → 연결한 앱에서 원하는 프로그램을 추가하세요. 아래 바로가기는 원하는 녹화 프로그램이 OBS Studio일 때만 해당합니다.",
"SharpShot 的录制使用 FFmpeg。你也可以链接已安装的录制程序，并在 SharpShot 里直接打开，不必打断当前流程。更复杂的应用（例如 OBS Studio）是常见选择。SharpShot 不附带该应用。它仍是独立程序，有自己的条款和隐私政策。请从仪表盘 → 已链接的应用添加任意程序。下面的快捷方式仅当你要打开的录制程序是 OBS Studio 时使用。",
),
"Show linked recorder button on the recording toolbar": ("Mostrar el botón de la grabadora vinculada en la barra de grabación", "Afficher le bouton de l'enregistreur lié dans la barre d'enregistrement", "Schaltfläche des verknüpften Recorders in der Aufnahmeliste anzeigen", "Mostrar o botão do gravador vinculado na barra de gravação", "Mostra il pulsante del registratore collegato nella barra di registrazione", "Показывать кнопку связанной программы записи на панели записи", "録画ツールバーにリンクした録画アプリのボタンを表示", "녹화 도구 모음에 연결한 녹화 프로그램 버튼 표시", "在录制工具栏显示已链接录制程序的按钮"),
"Adds a button to the recording menu for the recorder linked below. If none is linked yet, the button asks you to link one. OBS Studio is the recorder this shortcut looks for.": (
"Añade un botón al menú de grabación para la grabadora vinculada abajo. Si no hay ninguna, el botón pide vincular una. Este atajo busca OBS Studio.",
"Ajoute un bouton au menu d'enregistrement pour l'enregistreur lié ci-dessous. S'il n'y en a pas, le bouton demande d'en lier un. Ce raccourci cherche OBS Studio.",
"Fügt dem Aufnahmemenü eine Schaltfläche für das unten verknüpfte Programm hinzu. Ist keins verknüpft, fordert die Schaltfläche zum Verknüpfen auf. Diese Verknüpfung sucht OBS Studio.",
"Adiciona um botão ao menu de gravação para o gravador vinculado abaixo. Se não houver nenhum, o botão pede para vincular. Este atalho procura o OBS Studio.",
"Aggiunge un pulsante al menu di registrazione per il registratore collegato sotto. Se non ce n'è uno, il pulsante chiede di collegarlo. Questo collegamento cerca OBS Studio.",
"Добавляет кнопку в меню записи для программы, связанной ниже. Если ничего не связано, кнопка предложит связать. Этот ярлык ищет OBS Studio.",
"下でリンクした録画アプリ用のボタンを録画メニューに追加します。まだなければ、ボタンがリンクを求めます。このショートカットが探すのは OBS Studio です。",
"아래에서 연결한 녹화 프로그램 버튼을 녹화 메뉴에 넣습니다. 아직 없으면 버튼이 연결을 요청합니다. 이 바로가기가 찾는 프로그램은 OBS Studio입니다.",
"在录制菜单中为下方链接的录制程序添加按钮。如果尚未链接，按钮会请你先链接。此快捷方式查找的是 OBS Studio。",
),
"Linked recorder:": ("Grabadora vinculada:", "Enregistreur lié :", "Verknüpfter Recorder:", "Gravador vinculado:", "Registratore collegato:", "Связанная программа записи:", "リンクした録画アプリ:", "연결한 녹화 프로그램:", "已链接的录制程序："),
"Not linked": ("Sin vincular", "Non lié", "Nicht verknüpft", "Não vinculado", "Non collegato", "Не связано", "未リンク", "연결 안 됨", "未链接"),
"Detect": ("Detectar", "Détecter", "Erkennen", "Detectar", "Rileva", "Найти", "検出", "찾기", "检测"),
"Look for OBS Studio if that is the recorder you want this shortcut to open": (
"Busca OBS Studio si es la grabadora que quieres abrir con este atajo.",
"Cherche OBS Studio si c'est l'enregistreur que ce raccourci doit ouvrir.",
"Sucht OBS Studio, wenn dieses Programm über diese Verknüpfung geöffnet werden soll.",
"Procura o OBS Studio se for o gravador que este atalho deve abrir.",
"Cerca OBS Studio se è il registratore che questo collegamento deve aprire.",
"Ищет OBS Studio, если именно его должен открывать этот ярлык.",
"このショートカットで開きたい録画アプリが OBS Studio なら、それを探します。",
"이 바로가기로 열 녹화 프로그램이 OBS Studio라면 그것을 찾습니다.",
"如果此快捷方式要打开的录制程序是 OBS Studio，则查找它。",
),
"Change…": ("Cambiar…", "Modifier…", "Ändern…", "Alterar…", "Cambia…", "Изменить…", "変更…", "변경…", "更改…"),
"Choose a different recorder executable. This shortcut accepts obs64.exe or obs32.exe.": (
"Elige otro ejecutable de grabadora. Este atajo acepta obs64.exe u obs32.exe.",
"Choisissez un autre exécutable. Ce raccourci accepte obs64.exe ou obs32.exe.",
"Wählen Sie eine andere Programmdatei. Diese Verknüpfung akzeptiert obs64.exe oder obs32.exe.",
"Escolha outro executável. Este atalho aceita obs64.exe ou obs32.exe.",
"Scegli un altro eseguibile. Questo collegamento accetta obs64.exe o obs32.exe.",
"Выберите другой исполняемый файл. Этот ярлык принимает obs64.exe или obs32.exe.",
"別の実行ファイルを選びます。このショートカットが受け付けるのは obs64.exe か obs32.exe です。",
"다른 실행 파일을 고릅니다. 이 바로가기는 obs64.exe 또는 obs32.exe만 받습니다.",
"选择另一个录制程序可执行文件。此快捷方式只接受 obs64.exe 或 obs32.exe。",
),
"Unlink": ("Desvincular", "Dissocier", "Trennen", "Desvincular", "Scollega", "Отвязать", "リンク解除", "연결 해제", "取消链接"),
"Remove the linked recorder from this shortcut": ("Quita la grabadora vinculada de este atajo", "Retire l'enregistreur lié de ce raccourci", "Entfernt den verknüpften Recorder von dieser Verknüpfung", "Remove o gravador vinculado deste atalho", "Rimuove il registratore collegato da questo collegamento", "Убирает связанную программу с этого ярлыка", "このショートカットからリンクした録画アプリを外します", "이 바로가기에서 연결한 녹화 프로그램을 제거합니다", "从该快捷方式移除已链接的录制程序"),
"Audio Recording Mode:": ("Modo de audio de la grabación:", "Mode audio de l'enregistrement :", "Audio-Aufnahmemodus:", "Modo de áudio da gravação:", "Modalità audio di registrazione:", "Режим записи звука:", "音声の録音モード:", "오디오 녹음 모드:", "录音音频模式："),
"No Audio": ("Sin audio", "Sans audio", "Kein Audio", "Sem áudio", "Nessun audio", "Без звука", "音声なし", "오디오 없음", "无音频"),
"System Audio Only": ("Solo audio del sistema", "Audio système uniquement", "Nur Systemaudio", "Somente áudio do sistema", "Solo audio di sistema", "Только системный звук", "システム音声のみ", "시스템 오디오만", "仅系统音频"),
"Microphone Only": ("Solo micrófono", "Microphone uniquement", "Nur Mikrofon", "Somente microfone", "Solo microfono", "Только микрофон", "マイクのみ", "마이크만", "仅麦克风"),
"System Audio + Microphone": ("Audio del sistema + micrófono", "Audio système + microphone", "Systemaudio + Mikrofon", "Áudio do sistema + microfone", "Audio di sistema + microfono", "Системный звук + микрофон", "システム音声 + マイク", "시스템 오디오 + 마이크", "系统音频 + 麦克风"),
"FFmpeg region and full-screen recordings: capture system audio from the chosen playback device (WASAPI loopback). Choose No system audio for video-only.": (
"Grabaciones FFmpeg de región y pantalla completa: captura el audio del sistema del dispositivo de reproducción elegido (bucle WASAPI). Elige Sin audio del sistema para solo vídeo.",
"Enregistrements FFmpeg de région et plein écran : capture l'audio système de l'appareil de lecture choisi (boucle WASAPI). Choisissez Sans audio système pour la vidéo seule.",
"FFmpeg-Bereichs- und Vollbildaufnahmen: Systemaudio vom gewählten Wiedergabegerät (WASAPI-Loopback). Wählen Sie Kein Systemaudio für nur Video.",
"Gravações FFmpeg de região e tela cheia: captura o áudio do sistema do dispositivo de reprodução escolhido (loopback WASAPI). Escolha Sem áudio do sistema para só vídeo.",
"Registrazioni FFmpeg di regione e schermo intero: cattura l'audio di sistema dal dispositivo di riproduzione scelto (loopback WASAPI). Scegli Nessun audio di sistema per solo video.",
"Записи FFmpeg области и полного экрана: системный звук с выбранного устройства воспроизведения (петля WASAPI). Выберите «Без системного звука» для видео без звука.",
"FFmpeg の領域・全画面録画: 選んだ再生デバイスからシステム音声を取ります（WASAPI ループバック）。映像だけなら「システム音声なし」を選んでください。",
"FFmpeg 영역 및 전체 화면 녹화: 선택한 재생 장치에서 시스템 오디오를 받습니다(WASAPI 루프백). 영상만 원하면 시스템 오디오 없음을 고르세요.",
"FFmpeg 的区域和全屏录制：从所选播放设备采集系统音频（WASAPI 环回）。只要视频时请选择无系统音频。",
),
"FFmpeg - system audio (playback device):": ("FFmpeg: audio del sistema (dispositivo de reproducción):", "FFmpeg : audio système (appareil de lecture) :", "FFmpeg – Systemaudio (Wiedergabegerät):", "FFmpeg: áudio do sistema (dispositivo de reprodução):", "FFmpeg: audio di sistema (dispositivo di riproduzione):", "FFmpeg — системный звук (устройство воспроизведения):", "FFmpeg - システム音声（再生デバイス）:", "FFmpeg - 시스템 오디오(재생 장치):", "FFmpeg - 系统音频（播放设备）："),
"Uses WASAPI loopback on the selected output. Auto-detect uses the default playback device.": (
"Usa el bucle WASAPI de la salida elegida. La detección automática usa el dispositivo de reproducción predeterminado.",
"Utilise la boucle WASAPI de la sortie choisie. La détection automatique utilise l'appareil de lecture par défaut.",
"Nutzt WASAPI-Loopback am gewählten Ausgang. Auto-Erkennung verwendet das Standard-Wiedergabegerät.",
"Usa o loopback WASAPI da saída escolhida. A detecção automática usa o dispositivo de reprodução padrão.",
"Usa il loopback WASAPI dell'uscita scelta. Il rilevamento automatico usa il dispositivo di riproduzione predefinito.",
"Использует петлю WASAPI выбранного выхода. Автоопределение берёт устройство воспроизведения по умолчанию.",
"選んだ出力で WASAPI ループバックを使います。自動検出は既定の再生デバイスです。",
"선택한 출력에서 WASAPI 루프백을 사용합니다. 자동 찾기는 기본 재생 장치를 씁니다.",
"在所选输出上使用 WASAPI 环回。自动检测使用默认播放设备。",
),
"Input Audio Device (Microphone):": ("Dispositivo de entrada (micrófono):", "Périphérique d'entrée (microphone) :", "Eingabegerät (Mikrofon):", "Dispositivo de entrada (microfone):", "Dispositivo di input (microfono):", "Устройство ввода (микрофон):", "入力デバイス（マイク）:", "입력 장치(마이크):", "输入设备（麦克风）："),
"No system audio": ("Sin audio del sistema", "Sans audio système", "Kein Systemaudio", "Sem áudio do sistema", "Nessun audio di sistema", "Без системного звука", "システム音声なし", "시스템 오디오 없음", "无系统音频"),
"Auto-detect": ("Detectar automáticamente", "Détection automatique", "Automatisch erkennen", "Detectar automaticamente", "Rilevamento automatico", "Автоопределение", "自動検出", "자동 찾기", "自动检测"),
"Dashboard & windows": ("Panel y ventanas", "Tableau de bord et fenêtres", "Übersicht und Fenster", "Painel e janelas", "Pannello e finestre", "Панель и окна", "ダッシュボードとウィンドウ", "대시보드 및 창", "仪表盘和窗口"),
"Linked apps": ("Aplicaciones vinculadas", "Applications liées", "Verknüpfte Apps", "Aplicativos vinculados", "App collegate", "Связанные приложения", "リンクしたアプリ", "연결한 앱", "已链接的应用"),
"Add launchers to the main dashboard, the recording menu, or both. Choose an icon or up to 3 letters for each button.": (
"Añade accesos al panel principal, al menú de grabación o a ambos. Elige un icono o hasta 3 letras para cada botón.",
"Ajoutez des lanceurs au tableau de bord, au menu d'enregistrement ou aux deux. Choisissez une icône ou jusqu'à 3 lettres par bouton.",
"Fügen Sie Starter zur Übersicht, zum Aufnahmemenü oder zu beiden hinzu. Wählen Sie ein Symbol oder bis zu 3 Buchstaben pro Schaltfläche.",
"Adicione atalhos ao painel, ao menu de gravação ou a ambos. Escolha um ícone ou até 3 letras para cada botão.",
"Aggiungi avvii al pannello, al menu di registrazione o a entrambi. Scegli un'icona o fino a 3 lettere per ogni pulsante.",
"Добавьте кнопки запуска на панель, в меню записи или в оба места. Для каждой можно выбрать значок или до 3 букв.",
"メインのダッシュボード、録画メニュー、または両方に起動ボタンを追加します。各ボタンにアイコンか最大 3 文字を選べます。",
"메인 대시보드, 녹화 메뉴, 또는 둘 다에 실행 단추를 추가합니다. 각 단추에 아이콘이나 최대 3글자를 고르세요.",
"把启动按钮加到主仪表盘、录制菜单或两者。每个按钮可选图标或最多 3 个字母。",
),
"Add linked app…": ("Añadir aplicación vinculada…", "Ajouter une application liée…", "Verknüpfte App hinzufügen…", "Adicionar aplicativo vinculado…", "Aggiungi app collegata…", "Добавить связанное приложение…", "リンクしたアプリを追加…", "연결한 앱 추가…", "添加已链接的应用…"),
"Link another application. You can show it on the main dashboard, the recording menu, or both.": (
"Vincula otra aplicación. Puedes mostrarla en el panel principal, en el menú de grabación o en ambos.",
"Liez une autre application. Vous pouvez l'afficher sur le tableau de bord, dans le menu d'enregistrement ou les deux.",
"Verknüpfen Sie eine weitere App. Sie kann auf der Übersicht, im Aufnahmemenü oder an beiden Stellen erscheinen.",
"Vincule outro aplicativo. Você pode mostrá-lo no painel, no menu de gravação ou nos dois.",
"Collega un'altra applicazione. Puoi mostrarla sul pannello, nel menu di registrazione o in entrambi.",
"Свяжите другое приложение. Его можно показать на панели, в меню записи или в обоих местах.",
"別のアプリをリンクします。メインのダッシュボード、録画メニュー、または両方に表示できます。",
"다른 앱을 연결합니다. 메인 대시보드, 녹화 메뉴, 또는 둘 다에 표시할 수 있습니다.",
"链接另一个应用。可以显示在主仪表盘、录制菜单或两者上。",
),
"Display": ("Pantalla", "Affichage", "Anzeige", "Exibição", "Schermo", "Экран", "表示", "표시", "显示"),
"Screenshot Editor Display Monitor:": ("Monitor del editor de capturas:", "Écran de l'éditeur de captures :", "Monitor des Screenshot-Editors:", "Monitor do editor de capturas:", "Monitor dell'editor screenshot:", "Монитор редактора снимков:", "スクリーンショット エディターのモニター:", "스크린샷 편집기 모니터:", "截图编辑器所在显示器："),
"Choose which monitor displays the screenshot editor toolbar and preview when editing screenshots": (
"Elige qué monitor muestra la barra y la vista previa del editor al editar capturas.",
"Choisissez l'écran qui affiche la barre et l'aperçu de l'éditeur.",
"Wählen Sie den Monitor für Symbolleiste und Vorschau des Editors.",
"Escolha qual monitor mostra a barra e a prévia do editor ao editar capturas.",
"Scegli quale monitor mostra la barra e l'anteprima dell'editor.",
"Выберите монитор для панели и предпросмотра редактора.",
"編集時にツールバーとプレビューを出すモニターを選びます。",
"편집할 때 도구 모음과 미리 보기를 표시할 모니터를 고르세요.",
"选择编辑截图时显示编辑器工具栏和预览的显示器。",
),
"Dashboard Display Monitor:": ("Monitor del panel:", "Écran du tableau de bord :", "Monitor der Übersicht:", "Monitor do painel:", "Monitor del pannello:", "Монитор панели:", "ダッシュボードのモニター:", "대시보드 모니터:", "仪表盘所在显示器："),
"Choose which monitor shows the main SharpShot dashboard window": (
"Elige qué monitor muestra la ventana principal de SharpShot.",
"Choisissez l'écran qui affiche la fenêtre principale de SharpShot.",
"Wählen Sie den Monitor für das Hauptfenster von SharpShot.",
"Escolha qual monitor mostra a janela principal do SharpShot.",
"Scegli quale monitor mostra la finestra principale di SharpShot.",
"Выберите монитор для главного окна SharpShot.",
"SharpShot のメイン ウィンドウを出すモニターを選びます。",
"SharpShot 메인 창을 표시할 모니터를 고르세요.",
"选择显示 SharpShot 主窗口的显示器。",
),
"Dashboard window size (pixels):": ("Tamaño de la ventana del panel (píxeles):", "Taille de la fenêtre du tableau de bord (pixels) :", "Fenstergröße der Übersicht (Pixel):", "Tamanho da janela do painel (pixels):", "Dimensione finestra del pannello (pixel):", "Размер окна панели (пиксели):", "ダッシュボードのサイズ（ピクセル）:", "대시보드 창 크기(픽셀):", "仪表盘窗口大小（像素）："),
"Width": ("Ancho", "Largeur", "Breite", "Largura", "Larghezza", "Ширина", "幅", "너비", "宽度"),
"Dashboard width in logical pixels. Leave empty for default (618). Range: 280-2400.": (
"Ancho del panel en píxeles lógicos. Vacío = predeterminado (618). Intervalo: 280-2400.",
"Largeur du tableau de bord en pixels logiques. Vide = valeur par défaut (618). Plage : 280-2400.",
"Breite der Übersicht in logischen Pixeln. Leer = Standard (618). Bereich: 280-2400.",
"Largura do painel em pixels lógicos. Vazio = padrão (618). Intervalo: 280-2400.",
"Larghezza del pannello in pixel logici. Vuoto = predefinito (618). Intervallo: 280-2400.",
"Ширина панели в логических пикселях. Пусто = по умолчанию (618). Диапазон: 280-2400.",
"論理ピクセルでの幅。空欄は既定（618）。範囲: 280-2400。",
"논리 픽셀 기준 너비. 비우면 기본값(618). 범위: 280-2400.",
"仪表盘宽度（逻辑像素）。留空为默认值（618）。范围：280-2400。",
),
"Height": ("Alto", "Hauteur", "Höhe", "Altura", "Altezza", "Высота", "高さ", "높이", "高度"),
"Dashboard height in logical pixels. Leave empty for default (80). Range: 50-400.": (
"Alto del panel en píxeles lógicos. Vacío = predeterminado (80). Intervalo: 50-400.",
"Hauteur du tableau de bord en pixels logiques. Vide = valeur par défaut (80). Plage : 50-400.",
"Höhe der Übersicht in logischen Pixeln. Leer = Standard (80). Bereich: 50-400.",
"Altura do painel em pixels lógicos. Vazio = padrão (80). Intervalo: 50-400.",
"Altezza del pannello in pixel logici. Vuoto = predefinito (80). Intervallo: 50-400.",
"Высота панели в логических пикселях. Пусто = по умолчанию (80). Диапазон: 50-400.",
"論理ピクセルでの高さ。空欄は既定（80）。範囲: 50-400。",
"논리 픽셀 기준 높이. 비우면 기본값(80). 범위: 50-400.",
"仪表盘高度（逻辑像素）。留空为默认值（80）。范围：50-400。",
),
"Set width and height to the default dashboard size (618 x 80)": (
"Pone el ancho y el alto al tamaño predeterminado del panel (618 x 80).",
"Remet la largeur et la hauteur à la taille par défaut (618 x 80).",
"Setzt Breite und Höhe auf die Standardgröße (618 x 80).",
"Define largura e altura no tamanho padrão do painel (618 x 80).",
"Imposta larghezza e altezza sulla dimensione predefinita (618 x 80).",
"Ставит ширину и высоту на размер панели по умолчанию (618 x 80).",
"幅と高さをダッシュボードの既定サイズ（618 x 80）に戻します。",
"너비와 높이를 대시보드 기본 크기(618 x 80)로 맞춥니다.",
"将宽度和高度设为默认仪表盘大小（618 x 80）。",
),
"Reset to default": ("Restablecer", "Réinitialiser", "Standard wiederherstellen", "Redefinir", "Ripristina", "Сбросить", "既定に戻す", "기본값으로", "恢复默认"),
"Position & behavior": ("Posición y comportamiento", "Position et comportement", "Position und Verhalten", "Posição e comportamento", "Posizione e comportamento", "Положение и поведение", "位置と動作", "위치 및 동작", "位置和行为"),
"Restore dashboard to last position": ("Restaurar el panel en la última posición", "Restaurer le tableau de bord à la dernière position", "Übersicht an der letzten Position öffnen", "Restaurar o painel na última posição", "Ripristina il pannello nell'ultima posizione", "Восстанавливать панель в последней позиции", "ダッシュボードを最後の位置に戻す", "대시보드를 마지막 위치로 복원", "将仪表盘恢复到上次位置"),
"When enabled, SharpShot remembers where you moved the main dashboard window and restores it there on next launch. When disabled, the dashboard will always open in its default position on the selected monitor.": (
"Si está activo, SharpShot recuerda dónde moviste el panel y lo abre ahí la próxima vez. Si no, se abre siempre en la posición predeterminada del monitor elegido.",
"Si activé, SharpShot mémorise l'endroit où vous avez déplacé la fenêtre et l'y rouvre. Sinon, elle s'ouvre toujours à la position par défaut de l'écran choisi.",
"Wenn aktiv, merkt sich SharpShot, wohin Sie das Fenster verschoben haben, und öffnet es dort. Sonst erscheint es immer an der Standardposition des gewählten Monitors.",
"Se ativado, o SharpShot lembra para onde você moveu o painel e abre lá na próxima vez. Se não, abre sempre na posição padrão do monitor escolhido.",
"Se attivo, SharpShot ricorda dove hai spostato il pannello e lo riapre lì. Altrimenti si apre sempre nella posizione predefinita del monitor scelto.",
"Если включено, SharpShot запоминает, куда вы сдвинули панель, и открывает её там. Иначе она всегда открывается в позиции по умолчанию на выбранном мониторе.",
"オンにすると、ダッシュボードを動かした位置を覚えて次回そこで開きます。オフだと選んだモニターの既定位置で開きます。",
"켜면 대시보드를 옮긴 위치를 기억해 다음에 거기서 엽니다. 끄면 선택한 모니터의 기본 위치에서 항상 열립니다.",
"启用后，SharpShot 会记住你移动主窗口的位置，下次在那里打开。关闭后，仪表盘始终在所选显示器的默认位置打开。",
),
"After region capture, show dashboard on capture monitor": ("Tras una captura de región, mostrar el panel en el monitor de la captura", "Après une capture de région, afficher le tableau de bord sur l'écran de la capture", "Nach einer Bereichsaufnahme die Übersicht auf dem Aufnahmemonitor zeigen", "Após uma captura de região, mostrar o painel no monitor da captura", "Dopo una cattura di regione, mostra il pannello sul monitor della cattura", "После снимка области показывать панель на мониторе снимка", "領域キャプチャのあと、撮ったモニターにダッシュボードを表示", "영역 캡처 후, 캡처한 모니터에 대시보드 표시", "区域截图后，在截图所在显示器上显示仪表盘"),
"When enabled, the main SharpShot dashboard moves to the monitor where you took the region screenshot before showing the post-capture options.": (
"Si está activo, el panel se mueve al monitor donde tomaste la región antes de mostrar las opciones posteriores.",
"Si activé, le tableau de bord se place sur l'écran de la capture de région avant les options suivantes.",
"Wenn aktiv, wechselt die Übersicht vor den Folgeoptionen auf den Monitor der Bereichsaufnahme.",
"Se ativado, o painel vai para o monitor da captura de região antes das opções seguintes.",
"Se attivo, il pannello si sposta sul monitor della cattura di regione prima delle opzioni successive.",
"Если включено, панель переезжает на монитор снимка области перед меню следующих действий.",
"オンにすると、領域を撮ったモニターへダッシュボードが移ってから後続のメニューを出します。",
"켜면 영역을 찍은 모니터로 대시보드가 옮겨진 뒤 다음 메뉴가 나옵니다.",
"启用后，主窗口会先移到区域截图所在的显示器，再显示捕获后选项。",
),
"Then return dashboard to previous position": ("Luego devolver el panel a la posición anterior", "Puis remettre le tableau de bord à la position précédente", "Danach die Übersicht an die vorherige Position zurücksetzen", "Depois devolver o painel à posição anterior", "Poi riporta il pannello alla posizione precedente", "Затем вернуть панель на прежнее место", "そのあとダッシュボードを元の位置に戻す", "그런 다음 대시보드를 이전 위치로 되돌리기", "然后把仪表盘放回原位置"),
"When enabled, the dashboard is only moved to the capture monitor temporarily and then returned to where it was before the region capture.": (
"Si está activo, el panel se mueve al monitor de la captura solo un momento y luego vuelve a donde estaba.",
"Si activé, le tableau de bord n'est déplacé sur l'écran de la capture que le temps nécessaire, puis revient.",
"Wenn aktiv, wechselt die Übersicht nur vorübergehend auf den Aufnahmemonitor und kehrt dann zurück.",
"Se ativado, o painel vai ao monitor da captura só por um instante e depois volta.",
"Se attivo, il pannello si sposta sul monitor della cattura solo per un momento e poi torna.",
"Если включено, панель переезжает на монитор снимка только на время и затем возвращается.",
"オンにすると、ダッシュボードは撮ったモニターへ一時的に移り、そのあと元の位置に戻ります。",
"켜면 대시보드가 캡처한 모니터로 잠시 옮겨졌다가 원래 위치로 돌아옵니다.",
"启用后，仪表盘只是暂时移到截图显示器，然后回到区域截图之前的位置。",
),
"Open editor overlay on capture monitor": ("Abrir el editor en el monitor de la captura", "Ouvrir l'éditeur sur l'écran de la capture", "Editor auf dem Aufnahmemonitor öffnen", "Abrir o editor no monitor da captura", "Apri l'editor sul monitor della cattura", "Открывать редактор на мониторе снимка", "エディターを撮ったモニターで開く", "편집기를 캡처한 모니터에서 열기", "在截图所在显示器上打开编辑器"),
"When enabled, the screenshot editor opens on the same monitor where you took the screenshot, instead of always using the configured editor display monitor.": (
"Si está activo, el editor se abre en el monitor donde tomaste la captura, no siempre en el monitor configurado.",
"Si activé, l'éditeur s'ouvre sur l'écran de la capture, au lieu de l'écran configuré.",
"Wenn aktiv, öffnet der Editor auf dem Monitor der Aufnahme statt immer auf dem konfigurierten Editor-Monitor.",
"Se ativado, o editor abre no monitor da captura, e não sempre no monitor configurado.",
"Se attivo, l'editor si apre sul monitor della cattura, non sempre su quello configurato.",
"Если включено, редактор открывается на мониторе снимка, а не всегда на настроенном мониторе редактора.",
"オンにすると、設定したモニターではなく撮ったモニターでエディターが開きます。",
"켜면 설정된 모니터가 아니라 스크린샷을 찍은 모니터에서 편집기가 열립니다.",
"启用后，截图编辑器在截图所在显示器上打开，而不是始终使用已设置的编辑器显示器。",
),
"Tray & close": ("Bandeja y cierre", "Barre et fermeture", "Infobereich und Schließen", "Bandeja e fechar", "Area di notifica e chiusura", "Трей и закрытие", "トレイと閉じる", "트레이 및 닫기", "托盘和关闭"),
"When closing dashboard, minimize to tray instead of exiting": ("Al cerrar el panel, minimizar a la bandeja en lugar de salir", "En fermant le tableau de bord, réduire dans la barre au lieu de quitter", "Beim Schließen der Übersicht in den Infobereich minimieren statt beenden", "Ao fechar o painel, minimizar para a bandeja em vez de sair", "Alla chiusura del pannello, riduci a icona invece di uscire", "При закрытии панели сворачивать в трей, а не выходить", "ダッシュボードを閉じるとき終了せずトレイへ最小化", "대시보드를 닫을 때 종료하지 않고 트레이로 최소화", "关闭仪表盘时最小化到托盘而不是退出"),
"When enabled, clicking the Close button on the main SharpShot dashboard will minimize it to the tray. Use the tray menu's Exit option to fully close SharpShot.": (
"Si está activo, el botón Cerrar del panel lo minimiza a la bandeja. Usa Salir en el menú de la bandeja para cerrar SharpShot del todo.",
"Si activé, le bouton Fermer réduit la fenêtre dans la barre. Utilisez Quitter dans le menu de la barre pour fermer SharpShot.",
"Wenn aktiv, minimiert Schließen die Übersicht in den Infobereich. Beenden im Infobereichmenü schließt SharpShot ganz.",
"Se ativado, o botão Fechar do painel o minimiza na bandeja. Use Sair no menu da bandeja para fechar o SharpShot de vez.",
"Se attivo, Chiudi riduce il pannello a icona. Usa Esci nel menu dell'area di notifica per chiudere SharpShot.",
"Если включено, кнопка закрытия сворачивает панель в трей. Чтобы полностью закрыть SharpShot, выберите «Выход» в меню трея.",
"オンにすると、閉じるボタンはトレイへ最小化します。完全に終了するにはトレイメニューの終了を使います。",
"켜면 닫기 단추는 트레이로 최소화합니다. 완전히 끝내려면 트레이 메뉴의 종료를 사용하세요.",
"启用后，主窗口的关闭按钮会最小化到托盘。要完全退出 SharpShot，请使用托盘菜单中的退出。",
),
"Theme Customization:": ("Personalización del tema:", "Personnalisation du thème :", "Designanpassung:", "Personalização do tema:", "Personalizzazione del tema:", "Настройка оформления:", "テーマのカスタマイズ:", "테마 사용자 지정:", "主题自定义："),
"Icon Color:": ("Color del icono:", "Couleur de l'icône :", "Symbolfarbe:", "Cor do ícone:", "Colore icona:", "Цвет значка:", "アイコンの色:", "아이콘 색:", "图标颜色："),
"Use the RGB sliders to select a color": ("Usa los controles RGB para elegir un color", "Utilisez les curseurs RVB pour choisir une couleur", "Verwenden Sie die RGB-Regler, um eine Farbe zu wählen", "Use os controles RGB para escolher uma cor", "Usa i cursori RGB per scegliere un colore", "Выберите цвет ползунками RGB", "RGB スライダーで色を選びます", "RGB 슬라이더로 색을 고르세요", "用 RGB 滑块选择颜色"),
"Favorite colors": ("Colores favoritos", "Couleurs favorites", "Lieblingsfarben", "Cores favoritas", "Colori preferiti", "Избранные цвета", "お気に入りの色", "즐겨찾는 색", "收藏的颜色"),
"No saved colors yet.": ("Aún no hay colores guardados.", "Aucune couleur enregistrée.", "Noch keine gespeicherten Farben.", "Ainda não há cores salvas.", "Nessun colore salvato.", "Пока нет сохранённых цветов.", "保存した色はまだありません。", "저장한 색이 아직 없습니다.", "还没有保存的颜色。"),
"Save current color": ("Guardar el color actual", "Enregistrer la couleur actuelle", "Aktuelle Farbe speichern", "Salvar a cor atual", "Salva il colore attuale", "Сохранить текущий цвет", "現在の色を保存", "현재 색 저장", "保存当前颜色"),
"Turn on, then click swatches to remove favorites. Turn off when finished.": (
"Actívalo y haz clic en las muestras para quitar favoritos. Desactívalo al terminar.",
"Activez, puis cliquez sur les pastilles pour retirer des favoris. Désactivez ensuite.",
"Einschalten und Farbfelder anklicken, um Favoriten zu entfernen. Danach wieder ausschalten.",
"Ative e clique nas amostras para remover favoritos. Desative ao terminar.",
"Attivalo e fai clic sui campioni per rimuovere i preferiti. Disattivalo al termine.",
"Включите и нажимайте образцы, чтобы убрать избранные цвета. Затем выключите.",
"オンにしてから色見本をクリックするとお気に入りを消せます。終わったらオフにします。",
"켠 다음 색 견본을 클릭하면 즐겨찾기를 지웁니다. 끝나면 끄세요.",
"打开后点击色块即可移除收藏。完成后关闭。",
),
"Remove favorites": ("Quitar favoritos", "Retirer des favoris", "Favoriten entfernen", "Remover favoritos", "Rimuovi preferiti", "Удалить избранное", "お気に入りを削除", "즐겨찾기 제거", "移除收藏"),
"Done removing": ("Listo", "Terminé", "Fertig", "Concluído", "Fatto", "Готово", "完了", "완료", "完成"),
"Click a swatch to apply the color live.": ("Haz clic en una muestra para aplicar el color al momento.", "Cliquez sur une pastille pour appliquer la couleur tout de suite.", "Klicken Sie auf ein Farbfeld, um die Farbe sofort anzuwenden.", "Clique em uma amostra para aplicar a cor na hora.", "Fai clic su un campione per applicare il colore subito.", "Нажмите образец, чтобы сразу применить цвет.", "色見本をクリックするとすぐその色になります。", "색 견본을 클릭하면 바로 그 색이 적용됩니다.", "点击色块即可立即应用颜色。"),
"Hover Highlight Opacity:": ("Opacidad del resaltado al pasar el cursor:", "Opacité du surlignage au survol :", "Deckkraft der Hervorhebung beim Darüberfahren:", "Opacidade do destaque ao passar o cursor:", "Opacità evidenziazione al passaggio:", "Непрозрачность подсветки при наведении:", "ホバー強調の不透明度:", "가리킬 때 강조 불투명도:", "悬停高亮不透明度："),
"Drop Shadow Opacity:": ("Opacidad de la sombra:", "Opacité de l'ombre portée :", "Deckkraft des Schattens:", "Opacidade da sombra:", "Opacità dell'ombra:", "Непрозрачность тени:", "ドロップ シャドウの不透明度:", "그림자 불투명도:", "投影不透明度："),
"Hotkeys:": ("Atajos:", "Raccourcis :", "Tastenkürzel:", "Atalhos:", "Scorciatoie:", "Горячие клавиши:", "ホットキー:", "단축키:", "热键："),
"Click a hotkey field and press your combo (up to 3 keys). Examples: Ctrl+A, Shift+Ctrl+K, Shift+OemComma. Single modifiers (Ctrl, Shift, Alt) use triple-click mode.": (
"Haz clic en un campo y pulsa la combinación (hasta 3 teclas). Ejemplos: Ctrl+A, Shift+Ctrl+K, Shift+OemComma. Un solo modificador (Ctrl, Shift, Alt) usa el modo de triple clic.",
"Cliquez sur un champ et appuyez sur la combinaison (jusqu'à 3 touches). Exemples : Ctrl+A, Shift+Ctrl+K, Shift+OemComma. Un seul modificateur (Ctrl, Shift, Alt) utilise le triple clic.",
"Klicken Sie in ein Feld und drücken Sie die Kombination (bis zu 3 Tasten). Beispiele: Ctrl+A, Shift+Ctrl+K, Shift+OemComma. Einzelne Modifikatoren (Ctrl, Shift, Alt) nutzen den Dreifachklick.",
"Clique em um campo e pressione a combinação (até 3 teclas). Exemplos: Ctrl+A, Shift+Ctrl+K, Shift+OemComma. Um só modificador (Ctrl, Shift, Alt) usa o modo de clique triplo.",
"Fai clic su un campo e premi la combinazione (fino a 3 tasti). Esempi: Ctrl+A, Shift+Ctrl+K, Shift+OemComma. Un solo modificatore (Ctrl, Shift, Alt) usa il triplo clic.",
"Щёлкните поле и нажмите сочетание (до 3 клавиш). Примеры: Ctrl+A, Shift+Ctrl+K, Shift+OemComma. Одиночные модификаторы (Ctrl, Shift, Alt) работают как тройной щелчок.",
"フィールドをクリックして組み合わせを押します（最大 3 キー）。例: Ctrl+A、Shift+Ctrl+K、Shift+OemComma。Ctrl、Shift、Alt だけのときはトリプルクリックです。",
"칸을 클릭하고 조합을 누르세요(최대 3키). 예: Ctrl+A, Shift+Ctrl+K, Shift+OemComma. Ctrl, Shift, Alt만 쓰면 세 번 클릭 모드입니다.",
"点击热键栏并按下组合（最多 3 个键）。例如：Ctrl+A、Shift+Ctrl+K、Shift+OemComma。单独的 Ctrl、Shift、Alt 使用三击模式。",
),
"Screenshot Region Select:": ("Selección de región:", "Sélection de région :", "Bereichsauswahl:", "Seleção de região:", "Selezione regione:", "Выбор области:", "領域の選択:", "영역 선택:", "区域选择："),
"Remove hotkey": ("Quitar atajo", "Retirer le raccourci", "Tastenkürzel entfernen", "Remover atalho", "Rimuovi scorciatoia", "Удалить горячую клавишу", "ホットキーを削除", "단축키 제거", "移除热键"),
"Triple Click": ("Triple clic", "Triple clic", "Dreifachklick", "Clique triplo", "Triplo clic", "Тройной щелчок", "トリプルクリック", "세 번 클릭", "三击"),
"Screenshot Fullscreen:": ("Captura a pantalla completa:", "Capture plein écran :", "Vollbild-Screenshot:", "Captura em tela cheia:", "Screenshot a schermo intero:", "Снимок всего экрана:", "全画面スクリーンショット:", "전체 화면 스크린샷:", "全屏截图："),
"Record Region Select:": ("Grabar una región:", "Enregistrer une région :", "Bereich aufnehmen:", "Gravar uma região:", "Registra una regione:", "Запись области:", "領域を録画:", "영역 녹화:", "录制区域："),
"Record Fullscreen:": ("Grabar pantalla completa:", "Enregistrer en plein écran :", "Vollbild aufnehmen:", "Gravar tela cheia:", "Registra a schermo intero:", "Запись всего экрана:", "全画面を録画:", "전체 화면 녹화:", "录制全屏："),
"Copy:": ("Copiar:", "Copier :", "Kopieren:", "Copiar:", "Copia:", "Копировать:", "コピー:", "복사:", "复制："),
"Save:": ("Guardar:", "Enregistrer :", "Speichern:", "Salvar:", "Salva:", "Сохранить:", "保存:", "저장:", "保存："),
"Automatically check for updates": ("Buscar actualizaciones automáticamente", "Vérifier automatiquement les mises à jour", "Automatisch nach Updates suchen", "Verificar atualizações automaticamente", "Controlla automaticamente gli aggiornamenti", "Автоматически проверять обновления", "更新を自動で確認", "업데이트 자동 확인", "自动检查更新"),
"Check for updates manually:": ("Buscar actualizaciones manualmente:", "Vérifier les mises à jour manuellement :", "Manuell nach Updates suchen:", "Verificar atualizações manualmente:", "Controlla gli aggiornamenti manualmente:", "Проверить обновления вручную:", "更新を手動で確認:", "업데이트를 수동으로 확인:", "手动检查更新："),
"Check Now": ("Comprobar ahora", "Vérifier maintenant", "Jetzt prüfen", "Verificar agora", "Controlla ora", "Проверить", "今すぐ確認", "지금 확인", "立即检查"),
"Restore settings and hotkeys to the recommended profile. Click Save to keep changes.": (
"Restaura los ajustes y atajos al perfil recomendado. Pulsa Guardar para conservar los cambios.",
"Restaure les paramètres et raccourcis recommandés. Cliquez sur Enregistrer pour garder les changements.",
"Stellt Einstellungen und Tastenkürzel auf das empfohlene Profil zurück. Klicken Sie auf Speichern, um die Änderungen zu behalten.",
"Restaura as configurações e os atalhos para o perfil recomendado. Clique em Salvar para manter as mudanças.",
"Ripristina impostazioni e scorciatoie sul profilo consigliato. Fai clic su Salva per tenere le modifiche.",
"Возвращает параметры и горячие клавиши к рекомендованному профилю. Нажмите «Сохранить», чтобы оставить изменения.",
"設定とホットキーを推奨プロファイルに戻します。変更を残すには保存を押してください。",
"설정과 단축키를 권장 프로필로 되돌립니다. 변경을 유지하려면 저장을 누르세요.",
"将设置和热键恢复为推荐配置。点击保存以保留更改。",
),
"Reset to recommended defaults": ("Restablecer los valores recomendados", "Rétablir les valeurs recommandées", "Empfohlene Standardwerte wiederherstellen", "Redefinir para os padrões recomendados", "Ripristina i valori consigliati", "Вернуть рекомендованные значения", "推奨の既定に戻す", "권장 기본값으로 재설정", "恢复推荐默认值"),
"Cancel": ("Cancelar", "Annuler", "Abbrechen", "Cancelar", "Annulla", "Отмена", "キャンセル", "취소", "取消"),
"Save": ("Guardar", "Enregistrer", "Speichern", "Salvar", "Salva", "Сохранить", "保存", "저장", "保存"),
"Privacy": ("Privacidad", "Confidentialité", "Datenschutz", "Privacidade", "Privacy", "Конфиденциальность", "プライバシー", "개인정보", "隐私"),
"Privacy policy": ("Política de privacidad", "Politique de confidentialité", "Datenschutzrichtlinie", "Política de privacidade", "Informativa privacy", "Политика конфиденциальности", "プライバシー ポリシー", "개인정보 처리방침", "隐私政策"),
"Created by: BMOandShiro · ZHU Industries LLC": ("Creado por: BMOandShiro · ZHU Industries LLC", "Créé par : BMOandShiro · ZHU Industries LLC", "Erstellt von: BMOandShiro · ZHU Industries LLC", "Criado por: BMOandShiro · ZHU Industries LLC", "Creato da: BMOandShiro · ZHU Industries LLC", "Создано: BMOandShiro · ZHU Industries LLC", "作成: BMOandShiro · ZHU Industries LLC", "만든 사람: BMOandShiro · ZHU Industries LLC", "创建者：BMOandShiro · ZHU Industries LLC"),
"Not linked — use Detect or Change, or add any program from Dashboard → Linked apps": (
"Sin vincular: usa Detectar o Cambiar, o añade cualquier programa en Panel → Aplicaciones vinculadas",
"Non lié : utilisez Détecter ou Modifier, ou ajoutez un programme dans Tableau de bord → Applications liées",
"Nicht verknüpft – Erkennen oder Ändern, oder ein Programm unter Übersicht → Verknüpfte Apps hinzufügen",
"Não vinculado — use Detectar ou Alterar, ou adicione um programa em Painel → Aplicativos vinculados",
"Non collegato — usa Rileva o Cambia, oppure aggiungi un programma da Pannello → App collegate",
"Не связано — используйте «Найти» или «Изменить», либо добавьте программу: Панель → Связанные приложения",
"未リンク — 検出か変更を使うか、ダッシュボード → リンクしたアプリから追加してください",
"연결 안 됨 — 찾기 또는 변경을 쓰거나, 대시보드 → 연결한 앱에서 프로그램을 추가하세요",
"未链接 — 请使用检测或更改，或从仪表盘 → 已链接的应用添加任意程序",
),
"No linked apps yet. Use Add linked app… to choose an executable.": (
"Aún no hay aplicaciones vinculadas. Usa Añadir aplicación vinculada… para elegir un ejecutable.",
"Aucune application liée. Utilisez Ajouter une application liée… pour choisir un exécutable.",
"Noch keine verknüpften Apps. Verwenden Sie Verknüpfte App hinzufügen…, um eine Programmdatei zu wählen.",
"Ainda não há aplicativos vinculados. Use Adicionar aplicativo vinculado… para escolher um executável.",
"Nessuna app collegata. Usa Aggiungi app collegata… per scegliere un eseguibile.",
"Пока нет связанных приложений. Нажмите «Добавить связанное приложение…», чтобы выбрать файл.",
"リンクしたアプリはまだありません。「リンクしたアプリを追加…」で実行ファイルを選んでください。",
"연결한 앱이 아직 없습니다. 연결한 앱 추가…로 실행 파일을 고르세요.",
"还没有已链接的应用。使用“添加已链接的应用…”选择可执行文件。",
),
"Edit": ("Editar", "Modifier", "Bearbeiten", "Editar", "Modifica", "Изменить", "編集", "편집", "编辑"),
"Delete": ("Eliminar", "Supprimer", "Löschen", "Excluir", "Elimina", "Удалить", "削除", "삭제", "删除"),
"Press a key...": ("Pulsa una tecla...", "Appuyez sur une touche...", "Taste drücken...", "Pressione uma tecla...", "Premi un tasto...", "Нажмите клавишу...", "キーを押してください...", "키를 누르세요...", "请按键..."),
"Which SharpShot menu shows this button": ("En qué menú de SharpShot aparece este botón", "Quel menu SharpShot affiche ce bouton", "In welchem SharpShot-Menü diese Schaltfläche erscheint", "Em qual menu do SharpShot este botão aparece", "In quale menu di SharpShot compare questo pulsante", "В каком меню SharpShot показывать эту кнопку", "このボタンを出す SharpShot のメニュー", "이 단추를 표시할 SharpShot 메뉴", "此按钮显示在 SharpShot 的哪个菜单"),
"Toolbar icon": ("Icono de la barra", "Icône de la barre", "Symbol der Leiste", "Ícone da barra", "Icona della barra", "Значок панели", "ツールバーのアイコン", "도구 모음 아이콘", "工具栏图标"),
"Up to 3 letters shown on the button": ("Hasta 3 letras en el botón", "Jusqu'à 3 lettres sur le bouton", "Bis zu 3 Buchstaben auf der Schaltfläche", "Até 3 letras no botão", "Fino a 3 lettere sul pulsante", "До 3 букв на кнопке", "ボタンに最大 3 文字", "단추에 최대 3글자", "按钮上最多 3 个字母"),
"Choose a different executable": ("Elige otro ejecutable", "Choisissez un autre exécutable", "Andere Programmdatei wählen", "Escolha outro executável", "Scegli un altro eseguibile", "Выберите другой файл", "別の実行ファイルを選ぶ", "다른 실행 파일 선택", "选择另一个可执行文件"),
"Remove this linked app": ("Quitar esta aplicación vinculada", "Retirer cette application liée", "Diese verknüpfte App entfernen", "Remover este aplicativo vinculado", "Rimuovi questa app collegata", "Удалить это связанное приложение", "このリンクしたアプリを外す", "이 연결한 앱 제거", "移除此已链接的应用"),
"Smart Regions ON — click a highlight to copy text. Click again to turn off.": (
"Regiones inteligentes activadas: haz clic en un resaltado para copiar el texto. Otro clic las desactiva.",
"Régions intelligentes activées : cliquez sur une zone pour copier le texte. Cliquez encore pour désactiver.",
"Smart-Regionen an: Klicken Sie auf eine Markierung, um Text zu kopieren. Noch einmal klicken zum Ausschalten.",
"Regiões inteligentes ligadas: clique em um destaque para copiar o texto. Clique de novo para desligar.",
"Regioni intelligenti attive: fai clic su un'evidenziazione per copiare il testo. Clicca di nuovo per spegnere.",
"Умные области включены: щёлкните подсветку, чтобы скопировать текст. Ещё раз — выключить.",
"スマート領域オン — 強調表示をクリックして文字をコピー。もう一度でオフ。",
"스마트 영역 켜짐 — 강조를 클릭하면 글을 복사합니다. 다시 누르면 꺼집니다.",
"智能区域已开 — 点击高亮即可复制文字。再点一次关闭。",
),
"Smart Regions OFF — click to highlight content on the active window for quick text copy.": (
"Regiones inteligentes desactivadas: haz clic para resaltar el contenido de la ventana activa y copiar el texto.",
"Régions intelligentes désactivées : cliquez pour surligner le contenu de la fenêtre active et copier le texte.",
"Smart-Regionen aus: Klicken, um Inhalt im aktiven Fenster hervorzuheben und Text zu kopieren.",
"Regiões inteligentes desligadas: clique para destacar o conteúdo da janela ativa e copiar o texto.",
"Regioni intelligenti spente: fai clic per evidenziare il contenuto della finestra attiva e copiare il testo.",
"Умные области выключены: щёлкните, чтобы подсветить содержимое активного окна и быстро скопировать текст.",
"スマート領域オフ — クリックするとアクティブなウィンドウの内容を強調し、文字をすぐコピーできます。",
"스마트 영역 꺼짐 — 클릭하면 활성 창의 내용을 강조해 글을 바로 복사할 수 있습니다.",
"智能区域已关 — 点击后高亮当前窗口中的内容，以便快速复制文字。",
),
"Select Region": ("Seleccionar región", "Sélectionner une région", "Bereich wählen", "Selecionar região", "Seleziona regione", "Выбрать область", "領域を選択", "영역 선택", "选择区域"),
"Full Screen Screenshot": ("Captura a pantalla completa", "Capture plein écran", "Vollbild-Screenshot", "Captura em tela cheia", "Screenshot a schermo intero", "Снимок всего экрана", "全画面スクリーンショット", "전체 화면 스크린샷", "全屏截图"),
"OCR Region Capture": ("Captura de región OCR", "Capture de région OCR", "OCR-Bereichsaufnahme", "Captura de região OCR", "Acquisizione regione OCR", "OCR области", "OCR 領域キャプチャ", "OCR 영역 캡처", "OCR 区域截图"),
"OCR": ("OCR", "OCR", "OCR", "OCR", "OCR", "OCR", "OCR", "OCR", "OCR"),
"Smart": ("Smart", "Smart", "Smart", "Smart", "Smart", "Smart", "Smart", "Smart", "Smart"),
"Toggle Recording": ("Alternar grabación", "Basculer l'enregistrement", "Aufnahme umschalten", "Alternar gravação", "Attiva/disattiva registrazione", "Переключить запись", "録画の切り替え", "녹화 전환", "切换录制"),
"Minimize SharpShot": ("Minimizar SharpShot", "Réduire SharpShot", "SharpShot minimieren", "Minimizar o SharpShot", "Riduci SharpShot", "Свернуть SharpShot", "SharpShot を最小化", "SharpShot 최소화", "最小化 SharpShot"),
"Close SharpShot": ("Cerrar SharpShot", "Fermer SharpShot", "SharpShot schließen", "Fechar o SharpShot", "Chiudi SharpShot", "Закрыть SharpShot", "SharpShot を閉じる", "SharpShot 닫기", "关闭 SharpShot"),
"Copy to Clipboard": ("Copiar al portapapeles", "Copier dans le presse-papiers", "In die Zwischenablage kopieren", "Copiar para a área de transferência", "Copia negli appunti", "Копировать в буфер", "クリップボードにコピー", "클립보드에 복사", "复制到剪贴板"),
"Save File": ("Guardar archivo", "Enregistrer le fichier", "Datei speichern", "Salvar arquivo", "Salva file", "Сохранить файл", "ファイルを保存", "파일 저장", "保存文件"),
"Record Selected Region (FFmpeg)": ("Grabar la región seleccionada (FFmpeg)", "Enregistrer la région sélectionnée (FFmpeg)", "Ausgewählten Bereich aufnehmen (FFmpeg)", "Gravar a região selecionada (FFmpeg)", "Registra la regione selezionata (FFmpeg)", "Записать выбранную область (FFmpeg)", "選択した領域を録画 (FFmpeg)", "선택한 영역 녹화(FFmpeg)", "录制所选区域 (FFmpeg)"),
"Record Full Screen (FFmpeg)": ("Grabar pantalla completa (FFmpeg)", "Enregistrer en plein écran (FFmpeg)", "Vollbild aufnehmen (FFmpeg)", "Gravar tela cheia (FFmpeg)", "Registra a schermo intero (FFmpeg)", "Записать весь экран (FFmpeg)", "全画面を録画 (FFmpeg)", "전체 화면 녹화(FFmpeg)", "录制全屏 (FFmpeg)"),
"Launch OBS Studio": ("Abrir OBS Studio", "Lancer OBS Studio", "OBS Studio starten", "Abrir o OBS Studio", "Avvia OBS Studio", "Запустить OBS Studio", "OBS Studio を起動", "OBS Studio 실행", "启动 OBS Studio"),
"Cancel Recording": ("Cancelar grabación", "Annuler l'enregistrement", "Aufnahme abbrechen", "Cancelar gravação", "Annulla registrazione", "Отменить запись", "録画をキャンセル", "녹화 취소", "取消录制"),
"Stop Recording (FFmpeg)": ("Detener grabación (FFmpeg)", "Arrêter l'enregistrement (FFmpeg)", "Aufnahme stoppen (FFmpeg)", "Parar gravação (FFmpeg)", "Interrompi registrazione (FFmpeg)", "Остановить запись (FFmpeg)", "録画を停止 (FFmpeg)", "녹화 중지(FFmpeg)", "停止录制 (FFmpeg)"),
"Toggle Smart Regions — highlights text/content on the active window; click a highlight to copy text": (
"Alternar regiones inteligentes: resalta texto y contenido en la ventana activa; haz clic en un resaltado para copiar.",
"Basculer les régions intelligentes : surligne le texte de la fenêtre active ; cliquez pour copier.",
"Smart-Regionen umschalten: hebt Text im aktiven Fenster hervor; Klick kopiert den Text.",
"Alternar regiões inteligentes: destaca texto na janela ativa; clique para copiar.",
"Attiva regioni intelligenti: evidenzia il testo nella finestra attiva; clicca per copiare.",
"Умные области: подсвечивает текст в активном окне; щелчок копирует текст.",
"スマート領域の切り替え — アクティブなウィンドウの文字を強調。強調をクリックでコピー。",
"스마트 영역 전환 — 활성 창의 글을 강조합니다. 강조를 클릭하면 복사됩니다.",
"切换智能区域 — 高亮当前窗口中的文字；点击高亮即可复制。",
),
"Copy": ("Copiar", "Copier", "Kopieren", "Copiar", "Copia", "Копировать", "コピー", "복사", "复制"),
"Draw Boundary": ("Dibujar límite", "Dessiner une limite", "Grenze zeichnen", "Desenhar limite", "Disegna confine", "Нарисовать границу", "境界を描く", "경계 그리기", "绘制边界"),
"Drag to draw boundary box anywhere on screen. Press ESC to cancel.": (
"Arrastra para dibujar la caja de límite en cualquier parte de la pantalla. Esc cancela.",
"Faites glisser pour dessiner un cadre n'importe où. Échap annule.",
"Ziehen Sie, um irgendwo einen Grenzrahmen zu zeichnen. Esc bricht ab.",
"Arraste para desenhar a caixa de limite em qualquer lugar da tela. Esc cancela.",
"Trascina per disegnare il riquadro ovunque sullo schermo. Esc annulla.",
"Потяните, чтобы нарисовать рамку в любом месте экрана. Esc отменяет.",
"ドラッグして画面の好きな場所に境界ボックスを描きます。ESC でキャンセル。",
"끌어서 화면 어디에나 경계 상자를 그립니다. ESC는 취소입니다.",
"拖动即可在屏幕任意位置绘制边界框。按 ESC 取消。",
),
"Screenshot Captured": ("Captura realizada", "Capture effectuée", "Screenshot aufgenommen", "Captura feita", "Screenshot acquisito", "Снимок сделан", "スクリーンショットを撮りました", "스크린샷을 찍었습니다", "已截图"),
"What would you like to do with the screenshot?": ("¿Qué quieres hacer con la captura?", "Que voulez-vous faire de la capture ?", "Was möchten Sie mit dem Screenshot tun?", "O que você quer fazer com a captura?", "Cosa vuoi fare con lo screenshot?", "Что сделать со снимком?", "スクリーンショットをどうしますか？", "스크린샷을 어떻게 할까요?", "要如何处理这张截图？"),
"R:": ("R:", "R :", "R:", "R:", "R:", "R:", "R:", "R:", "R："),
"G:": ("G:", "V :", "G:", "G:", "G:", "G:", "G:", "G:", "G："),
"B:": ("B:", "B :", "B:", "B:", "B:", "B:", "B:", "B:", "B："),
"No": ("No", "Non", "Nein", "Não", "No", "Нет", "いいえ", "아니요", "否"),
"Yes": ("Sí", "Oui", "Ja", "Sim", "Sì", "Да", "はい", "예", "是"),
"The live copy is on GitHub. Paste that page into Steam and the Microsoft Store.": (
"La copia pública está en GitHub. Pega esa página en Steam y en Microsoft Store.",
"La copie publique est sur GitHub. Collez cette page dans Steam et le Microsoft Store.",
"Die öffentliche Fassung liegt auf GitHub. Fügen Sie diese Seite bei Steam und im Microsoft Store ein.",
"A cópia pública está no GitHub. Cole essa página na Steam e na Microsoft Store.",
"La copia pubblica è su GitHub. Incolla quella pagina in Steam e nel Microsoft Store.",
"Публичная копия на GitHub. Вставьте эту страницу в Steam и Microsoft Store.",
"公開版は GitHub にあります。そのページを Steam と Microsoft Store に貼ってください。",
"공개본은 GitHub에 있습니다. 그 페이지를 Steam과 Microsoft Store에 붙이세요.",
"公开版本在 GitHub。把该页面粘贴到 Steam 和 Microsoft Store。",
),
"Region Selection": ("Selección de región", "Sélection de région", "Bereichsauswahl", "Seleção de região", "Selezione regione", "Выбор области", "領域の選択", "영역 선택", "区域选择"),
"Click and drag to select a region, or press ESC to cancel": (
"Haz clic y arrastra para seleccionar una región, o pulsa Esc para cancelar.",
"Cliquez et faites glisser pour sélectionner une région, ou appuyez sur Échap pour annuler.",
"Klicken und ziehen, um einen Bereich zu wählen, oder Esc zum Abbrechen.",
"Clique e arraste para selecionar uma região, ou pressione Esc para cancelar.",
"Fai clic e trascina per selezionare una regione, oppure premi Esc per annullare.",
"Щёлкните и потяните, чтобы выбрать область, или нажмите Esc для отмены.",
"ドラッグして領域を選びます。ESC でキャンセル。",
"끌어서 영역을 선택하거나 ESC로 취소하세요.",
"单击并拖动以选择区域，或按 ESC 取消。",
),
"Edit Screenshot": ("Editar captura", "Modifier la capture", "Screenshot bearbeiten", "Editar captura", "Modifica screenshot", "Редактировать снимок", "スクリーンショットを編集", "스크린샷 편집", "编辑截图"),
}

def main():
    phrases = {}
    for lang in LANGS:
        phrases[lang] = {}
    for english, values in P.items():
        if len(values) != len(LANGS):
            raise SystemExit(f"Bad translation count for: {english[:60]} ({len(values)})")
        for lang, text in zip(LANGS, values):
            phrases[lang][english] = text
    out = Path(__file__).with_name("ui-phrases.json")
    out.write_text(json.dumps(phrases, ensure_ascii=False, indent=2), encoding="utf-8")
    print("phrases", len(P), "->", out)
    strings = Path(__file__).resolve().parents[1] / "_strings.txt"
    if strings.exists():
        missing = []
        for chunk in strings.read_text(encoding="utf-8").split("\n---\n"):
            key = chunk.replace("&amp;", "&").replace("&apos;", "'").strip()
            if not key or key in P:
                continue
            if key in {"PNG", "JPG", "BMP", "50", "#FFFF8C00", " | ", "200px", "12.5%", "15%"} or key.endswith("x"):
                continue
            missing.append(key)
        print("missing settings strings", len(missing))
        for item in missing:
            print("MISSING", item)

if __name__ == "__main__":
    main()
