# -*- coding: utf-8 -*-
"""Dutch (nl) UI phrase catalog. English text is the key."""

NL = {
"SharpShot Settings": "SharpShot-instellingen",
"Settings": "Instellingen",
"General": "Algemeen",
"Capture": "Vastleggen",
"Recording": "Opnemen",
"Dashboard": "Dashboard",
"Appearance": "Weergave",
"Hotkeys": "Sneltoetsen",
"Updates": "Updates",
"Language": "Taal",
"App language": "App-taal",
"Changes SharpShot's menus, settings, tooltips, and the in-app privacy policy. OCR language is separate.": "Wijzigt menu's, instellingen, knopinfo en het privacybeleid in de app. De OCR-taal is apart.",
"OCR language": "OCR-taal",
"Auto reads English, Spanish, French, German, Portuguese, and Italian together. Pick Japanese, Chinese, Korean, or Russian when the screen uses that script.": "Automatisch leest Engels, Spaans, Frans, Duits, Portugees en Italiaans samen. Kies Japans, Chinees, Koreaans of Russisch als het scherm dat schrift gebruikt.",
"Storage": "Opslag",
"Save Path:": "Opslagpad:",
"Browse": "Bladeren",
"Browse…": "Bladeren…",
"Screenshot Format:": "Screenshotformaat:",
"Startup & tray": "Opstarten en systeemvak",
"Enable Global Hotkeys": "Globale sneltoetsen inschakelen",
"Start Minimized": "Geminimaliseerd starten",
"Start SharpShot with Windows (minimized)": "SharpShot starten met Windows (geminimaliseerd)",
"Adds SharpShot to your Windows startup apps and starts it minimized to the tray when Windows starts": "Voegt SharpShot toe aan de Windows-opstartapps en start het geminimaliseerd in het systeemvak.",
"Notifications": "Meldingen",
"Disable all popup notifications": "Alle pop-upmeldingen uitschakelen",
"When enabled, all popup dialogs (success messages, file saved confirmations, etc.) will be suppressed": "Indien ingeschakeld worden pop-upvensters (succesberichten, bevestigingen van opgeslagen bestanden, enz.) verborgen.",
"Screen capture": "Schermvastlegging",
"Full-Screen Capture Target:": "Doel van volledig scherm:",
"All Screens": "Alle schermen",
"Primary Monitor": "Hoofdmonitor",
"Monitor 1": "Monitor 1",
"Monitor 2": "Monitor 2",
"Monitor 3": "Monitor 3",
"Monitor 4": "Monitor 4",
"Use GPU capture (DXGI) for faster screenshots": "GPU-vastlegging (DXGI) gebruiken voor snellere screenshots",
"Uses DXGI Desktop Duplication for region freeze-frames and fullscreen stills. Falls back to GDI if GPU capture fails. Leave off if you see blank images.": "Gebruikt DXGI Desktop Duplication voor bevroren regio's en volledige schermen. Valt terug op GDI als GPU-vastlegging mislukt. Uit laten als je lege beelden ziet.",
"After capture": "Na vastlegging",
"Auto-copy fullscreen and region screenshots to clipboard (failsafe after editor closes)": "Volledig scherm- en regiosscreenshots automatisch naar klembord (veiligheid na sluiten editor)",
"Automatically copies screenshots to clipboard after the editor closes, as a failsafe if you didn't copy in the editor. Applies to both fullscreen and region screenshots.": "Kopieert screenshots automatisch naar het klembord nadat de editor sluit, voor als je in de editor niet hebt gekopieerd. Geldt voor volledig scherm en regio.",
"Skip editor and auto-copy for region screenshots": "Editor overslaan en regio-screenshots automatisch kopiëren",
"When enabled, region screenshots will skip the editor overlay and automatically copy to clipboard for immediate pasting": "Indien ingeschakeld wordt de editor overgeslaan en gaat de regio-screenshot direct naar het klembord.",
"Adjust region before opening the editor": "Regio aanpassen vóór de editor",
"Freezes all monitors, then keeps the dashed selection on screen so you can drag the edges to resize before Enter opens the editor (or copies, if skip-editor is on). Esc cancels.": "Bevriest alle monitoren en houdt de gestippelde selectie zichtbaar zodat je de randen kunt slepen voordat Enter de editor opent (of kopieert als editor overslaan aan staat). Esc annuleert.",
"Show OCR quick-capture button on dashboard": "OCR-snelknop op dashboard tonen",
"Adds an OCR button to the main dashboard. Click it to region-select and extract text directly without opening the screenshot editor.": "Voegt een OCR-knop toe aan het hoofddashboard. Klik om een regio te selecteren en tekst te halen zonder de screenshot-editor.",
"Show Smart Regions toggle on dashboard (beta)": "Schakelaar Slimme regio's op dashboard tonen (bèta)",
"Adds a Smart toggle to the dashboard. When on, SharpShot highlights content regions on the active window so you can click to copy text.": "Voegt een Slim-schakelaar toe aan het dashboard. Indien aan markeert SharpShot inhoudsregio's in het actieve venster zodat je tekst kunt kopiëren.",
"Use dense OCR for Smart Regions (more text, slower) (beta)": "Dichte OCR voor Slimme regio's gebruiken (meer tekst, trager) (bèta)",
"Runs overlapping tiled OCR (SparseText + Auto) so Smart Regions find more on-screen text in browsers, games, and Electron apps. Turn off for a faster but thinner pass.": "Voert overlappende tegel-OCR uit (SparseText + Auto) zodat Slimme regio's meer tekst vinden in browsers, games en Electron-apps. Uit voor een snellere, dunnere pass.",
"Group Smart Region text (beta)": "Tekst van Slimme regio's groeperen (bèta)",
"Line": "Regel",
"Line: one box per row. Paragraph: join tight lines. Multiple paragraphs: join neighboring paragraphs.": "Regel: één vak per rij. Alinea: dichte regels samenvoegen. Meerdere alinea's: aangrenzende alinea's samenvoegen.",
"Paragraph": "Alinea",
"Multiple paragraphs": "Meerdere alinea's",
"Horizontal gap before split (beta)": "Horizontale ruimte vóór splitsen (bèta)",
"Widest": "Breedst",
"Splits a line only when neighboring words have a hole much larger than the sentence's own spacing. Off never splits. Widest is the smallest split. Close splits on smaller gaps.": "Splitst een regel alleen als buurwoorden een gat hebben dat veel groter is dan de eigen spatiering. Uit splitst nooit. Breedst is de kleinste split. Dicht splitst bij kleinere gaten.",
"Off": "Uit",
"Wide": "Breed",
"Close gaps": "Dichte gaten",
"Far apart": "Ver uit elkaar",
"Skip post-capture menu for screenshots and videos": "Menu na vastlegging overslaan voor screenshots en video's",
"When enabled, SharpShot skips the copy/save/cancel dashboard menu after region, fullscreen, and video captures.": "Indien ingeschakeld slaat SharpShot het kopiëren/opslaan/annuleren-menu over na regio-, volledig scherm- en video-opnames.",
"Hide SharpShot windows in screenshots (dashboard, editor, magnifier)": "SharpShot-vensters verbergen in screenshots (dashboard, editor, vergrootglas)",
"When enabled, SharpShot temporarily hides its own windows while the screen pixels are captured so they do not appear in the image. In the editor, the bottom toolbar, color panel, and OCR popup are hidden briefly when you save or copy so they are not baked into the file.": "Indien ingeschakeld verbergt SharpShot tijdelijk eigen vensters tijdens het vastleggen zodat ze niet in de afbeelding staan. In de editor worden de onderste werkbalk, het kleurenpaneel en de OCR-popup kort verborgen bij opslaan of kopiëren.",
"Magnifier": "Vergrootglas",
"Enable magnifier during region selection": "Vergrootglas inschakelen tijdens regioselectie",
"Magnifier Zoom Level:": "Zoomniveau vergrootglas:",
"Magnifier Size (Stationary):": "Vergrootglasgrootte (vast):",
"Magnifier Size (Follow/Auto):": "Vergrootglasgrootte (volgen/auto):",
"Magnifier Mode:": "Vergrootglasmodus:",
"Follow Cursor": "Cursor volgen",
"Stationary": "Vast",
"Auto (Stationary on non-100% monitors)": "Auto (vast op monitoren die niet op 100% staan)",
"Stationary Magnifier Settings:": "Instellingen vast vergrootglas:",
"Monitor:": "Monitor:",
"Position X (%):": "Positie X (%):",
"Position Y (%):": "Positie Y (%):",
"Position is relative to the selected monitor (0% = top/left, 100% = bottom/right)": "Positie is relatief ten opzichte van de geselecteerde monitor (0% = links/boven, 100% = rechts/onder)",
"Advanced magnifier (auto mode & boundary boxes)": "Geavanceerd vergrootglas (automodus en grensvakken)",
"Select monitors that should use stationary mode:": "Selecteer monitoren die vaste modus moeten gebruiken:",
"Checked monitors will automatically switch to stationary mode when your cursor enters them. Unchecked monitors will use follow cursor mode.": "Aangevinkte monitoren schakelen automatisch naar vaste modus als de cursor erin komt. Niet-aangevinkte gebruiken cursor volgen.",
"Boundary Boxes (for DPI-scaled monitors):": "Grensvakken (voor DPI-geschaalde monitoren):",
"If monitor detection doesn't work correctly (especially on any monitor that is not on 100% scaled zoom), you can draw custom boundary boxes. Checked boxes will trigger stationary mode when your cursor enters them. You can have multiple boxes per monitor.": "Als monitordetectie niet goed werkt (vooral op monitoren die niet op 100% zoom staan), kun je eigen grensvakken tekenen. Aangevinkte vakken activeren vaste modus. Je kunt meerdere vakken per monitor hebben.",
"Add Boundary Box": "Grensvak toevoegen",
"Video & audio": "Video en audio",
"Video Quality:": "Videokwaliteit:",
"High": "Hoog",
"Medium": "Gemiddeld",
"Low": "Laag",
"Screen recordings use FFmpeg.": "Schermopnames gebruiken FFmpeg.",
"Your own recorder": "Je eigen recorder",
"SharpShot recordings use FFmpeg. You can also link a recorder you already installed and open it from SharpShot without leaving your flow. A more advanced app such as OBS Studio is a common choice. SharpShot does not include that app. It stays separate, with its own terms and privacy policy. Add any program from Dashboard → Linked apps. The shortcut below is only if the recorder you want is OBS Studio.": "SharpShot-opnames gebruiken FFmpeg. Je kunt ook een recorder die je al hebt geïnstalleerd koppelen en vanuit SharpShot openen. Een geavanceerdere app zoals OBS Studio is een gangbare keuze. SharpShot bevat die app niet; die blijft apart, met eigen voorwaarden en privacybeleid. Voeg een programma toe via Dashboard → Gekoppelde apps. De snelkoppeling hieronder is alleen als je recorder OBS Studio is.",
"Show linked recorder button on the recording toolbar": "Knop gekoppelde recorder op de opnamebalk tonen",
"Adds a button to the recording menu for the recorder linked below. If none is linked yet, the button asks you to link one. OBS Studio is the recorder this shortcut looks for.": "Voegt een knop toe aan het opnamemenu voor de hieronder gekoppelde recorder. Is er nog geen gekoppeld, dan vraagt de knop er een te koppelen. Deze snelkoppeling zoekt naar OBS Studio.",
"Linked recorder:": "Gekoppelde recorder:",
"Not linked": "Niet gekoppeld",
"Detect": "Detecteren",
"Look for OBS Studio if that is the recorder you want this shortcut to open": "Zoek OBS Studio als dat de recorder is die deze snelkoppeling moet openen",
"Change…": "Wijzigen…",
"Choose a different recorder executable. This shortcut accepts obs64.exe or obs32.exe.": "Kies een ander recorderprogramma. Deze snelkoppeling accepteert obs64.exe of obs32.exe.",
"Unlink": "Ontkoppelen",
"Remove the linked recorder from this shortcut": "Verwijder de gekoppelde recorder van deze snelkoppeling",
"Audio Recording Mode:": "Audio-opnamemodus:",
"No Audio": "Geen audio",
"System Audio Only": "Alleen systeemaudio",
"Microphone Only": "Alleen microfoon",
"System Audio + Microphone": "Systeemaudio + microfoon",
"FFmpeg region and full-screen recordings: capture system audio from the chosen playback device (WASAPI loopback). Choose No system audio for video-only.": "FFmpeg regio- en volledig-schermopnames: systeemaudio van het gekozen afspeelapparaat (WASAPI-loopback). Kies Geen systeemaudio voor alleen video.",
"FFmpeg - system audio (playback device):": "FFmpeg - systeemaudio (afspeelapparaat):",
"Uses WASAPI loopback on the selected output. Auto-detect uses the default playback device.": "Gebruikt WASAPI-loopback op de geselecteerde uitvoer. Automatisch detecteren gebruikt het standaardafspeelapparaat.",
"Input Audio Device (Microphone):": "Invoeraudioapparaat (microfoon):",
"No system audio": "Geen systeemaudio",
"Auto-detect": "Automatisch detecteren",
"Dashboard & windows": "Dashboard en vensters",
"Linked apps": "Gekoppelde apps",
"Add launchers to the main dashboard, the recording menu, or both. Choose an icon or up to 3 letters for each button.": "Voeg starters toe aan het hoofddashboard, het opnamemenu of beide. Kies een pictogram of max. 3 letters per knop.",
"Add linked app…": "Gekoppelde app toevoegen…",
"Link another application. You can show it on the main dashboard, the recording menu, or both.": "Koppel een andere toepassing. Je kunt die tonen op het hoofddashboard, het opnamemenu of beide.",
"Display": "Beeldscherm",
"Screenshot Editor Display Monitor:": "Monitor voor screenshot-editor:",
"Choose which monitor displays the screenshot editor toolbar and preview when editing screenshots": "Kies op welke monitor de werkbalk en voorbeeld van de screenshot-editor verschijnen",
"Dashboard Display Monitor:": "Monitor voor dashboard:",
"Choose which monitor shows the main SharpShot dashboard window": "Kies op welke monitor het SharpShot-dashboardvenster verschijnt",
"Dashboard window size (pixels):": "Dashboardvenstergrootte (pixels):",
"Width": "Breedte",
"Dashboard width in logical pixels. Leave empty for default (618). Range: 280-2400.": "Dashboardbreedte in logische pixels. Leeg laten voor standaard (618). Bereik: 280–2400.",
"Height": "Hoogte",
"Dashboard height in logical pixels. Leave empty for default (80). Range: 50-400.": "Dashboardhoogte in logische pixels. Leeg laten voor standaard (80). Bereik: 50–400.",
"Set width and height to the default dashboard size (618 x 80)": "Breedte en hoogte op de standaard dashboardgrootte zetten (618 × 80)",
"Reset to default": "Standaard herstellen",
"Position & behavior": "Positie en gedrag",
"Restore dashboard to last position": "Dashboard op laatste positie herstellen",
"When enabled, SharpShot remembers where you moved the main dashboard window and restores it there on next launch. When disabled, the dashboard will always open in its default position on the selected monitor.": "Indien ingeschakeld onthoudt SharpShot waar je het dashboard hebt gezet en herstelt die positie bij de volgende start. Uit: altijd op de standaardpositie van de gekozen monitor.",
"After region capture, show dashboard on capture monitor": "Na regiovastlegging dashboard op vastlegmonitor tonen",
"When enabled, the main SharpShot dashboard moves to the monitor where you took the region screenshot before showing the post-capture options.": "Indien ingeschakeld verplaatst het dashboard naar de monitor van de regio-screenshot vóór de opties na vastlegging.",
"Then return dashboard to previous position": "Daarna dashboard terugzetten naar vorige positie",
"When enabled, the dashboard is only moved to the capture monitor temporarily and then returned to where it was before the region capture.": "Indien ingeschakeld wordt het dashboard tijdelijk naar de vastlegmonitor verplaatst en daarna teruggezet.",
"Open editor overlay on capture monitor": "Editor-overlay op vastlegmonitor openen",
"When enabled, the screenshot editor opens on the same monitor where you took the screenshot, instead of always using the configured editor display monitor.": "Indien ingeschakeld opent de screenshot-editor op dezelfde monitor als de screenshot, in plaats van altijd de ingestelde editormonitor.",
"Tray & close": "Systeemvak en sluiten",
"When closing dashboard, minimize to tray instead of exiting": "Bij sluiten van dashboard minimaliseren naar systeemvak i.p.v. afsluiten",
"When enabled, clicking the Close button on the main SharpShot dashboard will minimize it to the tray. Use the tray menu's Exit option to fully close SharpShot.": "Indien ingeschakeld minimaliseert de Sluiten-knop op het dashboard naar het systeemvak. Gebruik Afsluiten in het systeemvakmenu om SharpShot volledig te sluiten.",
"Theme Customization:": "Thema aanpassen:",
"Icon Color:": "Pictogramkleur:",
"Use the RGB sliders to select a color": "Gebruik de RGB-schuifregelaars om een kleur te kiezen",
"Favorite colors": "Favoriete kleuren",
"No saved colors yet.": "Nog geen opgeslagen kleuren.",
"Save current color": "Huidige kleur opslaan",
"Turn on, then click swatches to remove favorites. Turn off when finished.": "Zet aan en klik op stalen om favorieten te verwijderen. Zet uit als je klaar bent.",
"Remove favorites": "Favorieten verwijderen",
"Done removing": "Klaar met verwijderen",
"Click a swatch to apply the color live.": "Klik op een staal om de kleur live toe te passen.",
"Hover Highlight Opacity:": "Dekking markering bij hover:",
"Drop Shadow Opacity:": "Dekking slagschaduw:",
"Hotkeys:": "Sneltoetsen:",
"Click a hotkey field and press your combo (up to 3 keys). Examples: Ctrl+A, Shift+Ctrl+K, Shift+OemComma. Single modifiers (Ctrl, Shift, Alt) use triple-click mode.": "Klik op een sneltoetsveld en druk je combinatie (max. 3 toetsen). Voorbeelden: Ctrl+A, Shift+Ctrl+K, Shift+OemComma. Alleen modifiers (Ctrl, Shift, Alt) gebruiken driedubbelklik-modus.",
"Screenshot Region Select:": "Screenshot regioselectie:",
"Remove hotkey": "Sneltoets verwijderen",
"Triple Click": "Driedubbelklik",
"Screenshot Fullscreen:": "Screenshot volledig scherm:",
"Record Region Select:": "Regio opnemen:",
"Record Fullscreen:": "Volledig scherm opnemen:",
"Copy:": "Kopiëren:",
"Save:": "Opslaan:",
"Automatically check for updates": "Automatisch controleren op updates",
"Check for updates manually:": "Handmatig controleren op updates:",
"Check Now": "Nu controleren",
"Restore settings and hotkeys to the recommended profile. Click Save to keep changes.": "Instellingen en sneltoetsen herstellen naar het aanbevolen profiel. Klik op Opslaan om te bewaren.",
"Reset to recommended defaults": "Aanbevolen standaardwaarden herstellen",
"Cancel": "Annuleren",
"Save": "Opslaan",
"Privacy": "Privacy",
"Privacy policy": "Privacybeleid",
"Created by: BMOandShiro · ZHU Industries LLC": "Gemaakt door: BMOandShiro · ZHU Industries LLC",
"Not linked — use Detect or Change, or add any program from Dashboard → Linked apps": "Niet gekoppeld — gebruik Detecteren of Wijzigen, of voeg een programma toe via Dashboard → Gekoppelde apps",
"No linked apps yet. Use Add linked app… to choose an executable.": "Nog geen gekoppelde apps. Gebruik Gekoppelde app toevoegen… om een programma te kiezen.",
"Edit": "Bewerken",
"Delete": "Verwijderen",
"Press a key...": "Druk op een toets...",
"Which SharpShot menu shows this button": "In welk SharpShot-menu deze knop staat",
"Toolbar icon": "Werkbalkpictogram",
"Up to 3 letters shown on the button": "Maximaal 3 letters op de knop",
"Choose a different executable": "Ander programma kiezen",
"Remove this linked app": "Deze gekoppelde app verwijderen",
"Smart Regions ON — click a highlight to copy text. Click again to turn off.": "Slimme regio's AAN — klik op een markering om tekst te kopiëren. Opnieuw klikken om uit te zetten.",
"Smart Regions OFF — click to highlight content on the active window for quick text copy.": "Slimme regio's UIT — klik om inhoud in het actieve venster te markeren voor snel kopiëren.",
"Select Region": "Regio selecteren",
"Full Screen Screenshot": "Screenshot volledig scherm",
"OCR Region Capture": "OCR-regiovastlegging",
"OCR": "OCR",
"Smart": "Slim",
"Toggle Recording": "Opname schakelen",
"Minimize SharpShot": "SharpShot minimaliseren",
"Close SharpShot": "SharpShot sluiten",
"Copy to Clipboard": "Naar klembord kopiëren",
"Save File": "Bestand opslaan",
"Record Selected Region (FFmpeg)": "Geselecteerde regio opnemen (FFmpeg)",
"Record Full Screen (FFmpeg)": "Volledig scherm opnemen (FFmpeg)",
"Launch OBS Studio": "OBS Studio starten",
"Cancel Recording": "Opname annuleren",
"Stop Recording (FFmpeg)": "Opname stoppen (FFmpeg)",
"Toggle Smart Regions — highlights text/content on the active window; click a highlight to copy text": "Slimme regio's schakelen — markeert tekst/inhoud in het actieve venster; klik om te kopiëren",
"Copy": "Kopiëren",
"Draw Boundary": "Grens tekenen",
"Drag to draw boundary box anywhere on screen. Press ESC to cancel.": "Sleep om overal op het scherm een grensvak te tekenen. Druk op ESC om te annuleren.",
"Screenshot Captured": "Screenshot vastgelegd",
"What would you like to do with the screenshot?": "Wat wil je met de screenshot doen?",
"R:": "R:",
"G:": "G:",
"B:": "B:",
"No": "Nee",
"Yes": "Ja",
"The live copy is on GitHub. Paste that page into Steam and the Microsoft Store.": "De actuele tekst staat op GitHub. Plak die pagina in Steam en de Microsoft Store.",
"Region Selection": "Regioselectie",
"Click and drag to select a region, or press ESC to cancel": "Klik en sleep om een regio te selecteren, of druk op ESC om te annuleren",
"Edit Screenshot": "Screenshot bewerken",
}
